

create type color as enum(
    'Black',
    'Blush',
    'Dark Blue',
    'Light Blue',
    'Eggplant',
    'Kale',
    'Lavender',
    'Licorice',
    'Mustard',
    'Nude',
    'Peach',
    'Pistachio',
    'Platinum',
    'Red',
    'Stone',
    'Tangerine',
    'Terracotta',
    'Turquoise',
    'White'
);


create type product as enum(
     'Atlanta',
     'Boston',
     'Carmel',
     'Charleston',
     'Chicago',
     'Concrete Drain Covers',
     'Denver',
     'HD Round',
     'Houston',
     'Manhattan',
     'Mini Manhattan',
     'Miami',
     'Mini Miami',
     'Michu',
     'Michu Planter',
     'Minima',
     'New York',
     'New York 100',
     'Orlando',
     'Portland',
     'Phoenix',
     'Reno',
     'San Francisco New Mold',
     'San Francisco Old Mold',
     'San Francisco ADA',
     'Mini San Francisco',
     'Seattle',
     'Texas',
     'Vegas 80',
     'Vegas 60',
     'Venice',
     'Washington',
     'Inner Planter',
     'Outer Planter'
);


create type phase as enum(
    'In Production', 
    'Produced', 
    'In Stock'
);



CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    color color NOT NULL,
    product product NOT NULL,
    amount INTEGER NOT NULL,
    prty_lvl INTEGER NOT NULL,
    phase phase NOT NULL
);