BEGIN;


INSERT INTO "orders" ("color", "product", "amount", "prty_lvl", "phase")
VALUES 
('Black', 'San Diego', 0, 0, 'In Production'), 
('Black', 'San Diego', 0, 0, 'Produced'),
('Black', 'San Diego', 0, 0, 'In Stock'),
('Black', 'Atlanta -NF', 0, 0, 'In Production'),
('Black', 'Atlanta -NF', 0, 0, 'Produced'),
('Black', 'Atlanta -NF', 0, 0, 'In Stock'),
('Blush', 'San Diego', 0, 0, 'In Production'),
('Blush', 'San Diego', 0, 0, 'Produced'),
('Blush', 'San Diego', 0, 0, 'In Stock'),
('Blush', 'Atlanta -NF', 0, 0, 'In Production'),
('Blush', 'Atlanta -NF', 0, 0, 'Produced'),
('Blush', 'Atlanta -NF', 0, 0, 'In Stock'),
('Dark Blue', 'San Diego', 0, 0, 'In Production'),
('Dark Blue', 'San Diego', 0, 0, 'Produced'),
('Dark Blue', 'San Diego', 0, 0, 'In Stock'),
('Dark Blue', 'Atlanta -NF', 0, 0, 'In Production'),
('Dark Blue', 'Atlanta -NF', 0, 0, 'Produced'),
('Dark Blue', 'Atlanta -NF', 0, 0, 'In Stock'),
('Light Blue', 'San Diego', 0, 0, 'In Production'),
('Light Blue', 'San Diego', 0, 0, 'Produced'),
('Light Blue', 'San Diego', 0, 0, 'In Stock'),
('Light Blue', 'Atlanta -NF', 0, 0, 'In Production'),
('Light Blue', 'Atlanta -NF', 0, 0, 'Produced'),
('Light Blue', 'Atlanta -NF', 0, 0, 'In Stock'),
('Eggplant', 'San Diego', 0, 0, 'In Production'),
('Eggplant', 'San Diego', 0, 0, 'Produced'),
('Eggplant', 'San Diego', 0, 0, 'In Stock'),
('Eggplant', 'Atlanta -NF', 0, 0, 'In Production'),
('Eggplant', 'Atlanta -NF', 0, 0, 'Produced'),
('Eggplant', 'Atlanta -NF', 0, 0, 'In Stock'),
('Kale', 'San Diego', 0, 0, 'In Production'),
('Kale', 'San Diego', 0, 0, 'Produced'),
('Kale', 'San Diego', 0, 0, 'In Stock'),
('Kale', 'Atlanta -NF', 0, 0, 'In Production'),
('Kale', 'Atlanta -NF', 0, 0, 'Produced'),
('Kale', 'Atlanta -NF', 0, 0, 'In Stock'),
('Lavender', 'San Diego', 0, 0, 'In Production'),
('Lavender', 'San Diego', 0, 0, 'Produced'),
('Lavender', 'San Diego', 0, 0, 'In Stock'),
('Lavender', 'Atlanta -NF', 0, 0, 'In Production'),
('Lavender', 'Atlanta -NF', 0, 0, 'Produced'),
('Lavender', 'Atlanta -NF', 0, 0, 'In Stock'),
('Licorice', 'San Diego', 0, 0, 'In Production'),
('Licorice', 'San Diego', 0, 0, 'Produced'),
('Licorice', 'San Diego', 0, 0, 'In Stock'),
('Licorice', 'Atlanta -NF', 0, 0, 'In Production'),
('Licorice', 'Atlanta -NF', 0, 0, 'Produced'),
('Licorice', 'Atlanta -NF', 0, 0, 'In Stock'),
('Mustard', 'San Diego', 0, 0, 'In Production'),
('Mustard', 'San Diego', 0, 0, 'Produced'),
('Mustard', 'San Diego', 0, 0, 'In Stock'),
('Mustard', 'Atlanta -NF', 0, 0, 'In Production'),
('Mustard', 'Atlanta -NF', 0, 0, 'Produced'),
('Mustard', 'Atlanta -NF', 0, 0, 'In Stock'),
('Nude', 'San Diego', 0, 0, 'In Production'),
('Nude', 'San Diego', 0, 0, 'Produced'),
('Nude', 'San Diego', 0, 0, 'In Stock'),
('Nude', 'Atlanta -NF', 0, 0, 'In Production'),
('Nude', 'Atlanta -NF', 0, 0, 'Produced'),
('Nude', 'Atlanta -NF', 0, 0, 'In Stock'),
('Peach', 'San Diego', 0, 0, 'In Production'),
('Peach', 'San Diego', 0, 0, 'Produced'),
('Peach', 'San Diego', 0, 0, 'In Stock'),
('Peach', 'Atlanta -NF', 0, 0, 'In Production'),
('Peach', 'Atlanta -NF', 0, 0, 'Produced'),
('Peach', 'Atlanta -NF', 0, 0, 'In Stock'),
('Pistachio', 'San Diego', 0, 0, 'In Production'),
('Pistachio', 'San Diego', 0, 0, 'Produced'),
('Pistachio', 'San Diego', 0, 0, 'In Stock'),
('Pistachio', 'Atlanta -NF', 0, 0, 'In Production'),
('Pistachio', 'Atlanta -NF', 0, 0, 'Produced'),
('Pistachio', 'Atlanta -NF', 0, 0, 'In Stock'),
('Platinum', 'San Diego', 0, 0, 'In Production'),
('Platinum', 'San Diego', 0, 0, 'Produced'),
('Platinum', 'San Diego', 0, 0, 'In Stock'),
('Platinum', 'Atlanta -NF', 0, 0, 'In Production'),
('Platinum', 'Atlanta -NF', 0, 0, 'Produced'),
('Platinum', 'Atlanta -NF', 0, 0, 'In Stock'),
('Red', 'San Diego', 0, 0, 'In Production'),
('Red', 'San Diego', 0, 0, 'Produced'),
('Red', 'San Diego', 0, 0, 'In Stock'),
('Red', 'Atlanta -NF', 0, 0, 'In Production'),
('Red', 'Atlanta -NF', 0, 0, 'Produced'),
('Red', 'Atlanta -NF', 0, 0, 'In Stock'),
('Stone', 'San Diego', 0, 0, 'In Production'),
('Stone', 'San Diego', 0, 0, 'Produced'),
('Stone', 'San Diego', 0, 0, 'In Stock'),
('Stone', 'Atlanta -NF', 0, 0, 'In Production'),
('Stone', 'Atlanta -NF', 0, 0, 'Produced'),
('Stone', 'Atlanta -NF', 0, 0, 'In Stock'),
('Tangerine', 'San Diego', 0, 0, 'In Production'),
('Tangerine', 'San Diego', 0, 0, 'Produced'),
('Tangerine', 'San Diego', 0, 0, 'In Stock'),
('Tangerine', 'Atlanta -NF', 0, 0, 'In Production'),
('Tangerine', 'Atlanta -NF', 0, 0, 'Produced'),
('Tangerine', 'Atlanta -NF', 0, 0, 'In Stock'),
('Terracotta', 'San Diego', 0, 0, 'In Production'),
('Terracotta', 'San Diego', 0, 0, 'Produced'),
('Terracotta', 'San Diego', 0, 0, 'In Stock'),
('Terracotta', 'Atlanta -NF', 0, 0, 'In Production'),
('Terracotta', 'Atlanta -NF', 0, 0, 'Produced'),
('Terracotta', 'Atlanta -NF', 0, 0, 'In Stock'),
('Turquoise', 'San Diego', 0, 0, 'In Production'),
('Turquoise', 'San Diego', 0, 0, 'Produced'),
('Turquoise', 'San Diego', 0, 0, 'In Stock'),
('Turquoise', 'Atlanta -NF', 0, 0, 'In Production'),
('Turquoise', 'Atlanta -NF', 0, 0, 'Produced'),
('Turquoise', 'Atlanta -NF', 0, 0, 'In Stock'),
('White', 'San Diego', 0, 0, 'In Production'),
('White', 'San Diego', 0, 0, 'Produced'),
('White', 'San Diego', 0, 0, 'In Stock'),
('White', 'Atlanta -NF', 0, 0, 'In Production'),
('White', 'Atlanta -NF', 0, 0, 'Produced'),
('White', 'Atlanta -NF', 0, 0, 'In Stock');

COMMIT;