--USE DATATOINSERT FOR BACKEND SEEDING
--USE ORDERMAP FOR FRONTEND SEEDING

BEGIN;

TRUNCATE
    "users", "orders";

select setval('orders_order_id_seq', 1, false);

INSERT INTO "users" ("user_department", "user_password", "is_admin")
VALUES
    ('admin', '$2y$12$GdIB9QwYVi4IU7v80VydP.McTWu35tnUBGPyuWHyov0KkxAw.zgR2', true), --Admin2021
    ('Production', '$2y$12$z1yPB1y8d8VXc2iaK2o1EO.t6eWrO7j1o3BBIEkGU3PWR7Yyzstwu', false), --Prod2021
    ('shipping', '$2y$12$lSqp8.dC16/iBp5mOKj3ueMNt4RDXkIcVvQnQNJLTW3f.mP5NToK.', false); --Ship2021

INSERT INTO "orders" ("color", "product", "amount", "prty_lvl", "phase")
VALUES 
('Black', 'Atlanta', 0, 0, 'In Production'), 
('Black', 'Atlanta', 0, 0, 'Produced'),
('Black', 'Atlanta', 0, 0, 'In Stock'),
('Black', 'Boston', 0, 0, 'In Production'),
('Black', 'Boston', 0, 0, 'Produced'),
('Black', 'Boston', 0, 0, 'In Stock'),
('Black', 'Carmel', 0, 0, 'In Production'),
('Black', 'Carmel', 0, 0, 'Produced'),
('Black', 'Carmel', 0, 0, 'In Stock'),
('Black', 'Charleston', 0, 0, 'In Production'),
('Black', 'Charleston', 0, 0, 'Produced'),
('Black', 'Charleston', 0, 0, 'In Stock'),
('Black', 'Chicago', 0, 0, 'In Production'),
('Black', 'Chicago', 0, 0, 'Produced'),
('Black', 'Chicago', 0, 0, 'In Stock'),
('Black', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Black', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Black', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Black', 'Denver', 0, 0, 'In Production'),
('Black', 'Denver', 0, 0, 'Produced'),
('Black', 'Denver', 0, 0, 'In Stock'),
('Black', 'HD Round', 0, 0, 'In Production'),
('Black', 'HD Round', 0, 0, 'Produced'),
('Black', 'HD Round', 0, 0, 'In Stock'),
('Black', 'Houston', 0, 0, 'In Production'),
('Black', 'Houston', 0, 0, 'Produced'),
('Black', 'Houston', 0, 0, 'In Stock'),
('Black', 'Manhattan', 0, 0, 'In Production'),
('Black', 'Manhattan', 0, 0, 'Produced'),
('Black', 'Manhattan', 0, 0, 'In Stock'),
('Black', 'Mini Manhattan', 0, 0, 'In Production'),
('Black', 'Mini Manhattan', 0, 0, 'Produced'),
('Black', 'Mini Manhattan', 0, 0, 'In Stock'),
('Black', 'Miami', 0, 0, 'In Production'),
('Black', 'Miami', 0, 0, 'Produced'),
('Black', 'Miami', 0, 0, 'In Stock'),
('Black', 'Mini Miami', 0, 0, 'In Production'),
('Black', 'Mini Miami', 0, 0, 'Produced'),
('Black', 'Mini Miami', 0, 0, 'In Stock'),
('Black', 'Michu', 0, 0, 'In Production'),
('Black', 'Michu', 0, 0, 'Produced'),
('Black', 'Michu', 0, 0, 'In Stock'),
('Black', 'Michu Planter', 0, 0, 'In Production'),
('Black', 'Michu Planter', 0, 0, 'Produced'),
('Black', 'Michu Planter', 0, 0, 'In Stock'),
('Black', 'Minima', 0, 0, 'In Production'),
('Black', 'Minima', 0, 0, 'Produced'),
('Black', 'Minima', 0, 0, 'In Stock'),
('Black', 'New York', 0, 0, 'In Production'),
('Black', 'New York', 0, 0, 'Produced'),
('Black', 'New York', 0, 0, 'In Stock'),
('Black', 'New York 100', 0, 0, 'In Production'),
('Black', 'New York 100', 0, 0, 'Produced'),
('Black', 'New York 100', 0, 0, 'In Stock'),
('Black', 'Orlando', 0, 0, 'In Production'),
('Black', 'Orlando', 0, 0, 'Produced'),
('Black', 'Orlando', 0, 0, 'In Stock'),
('Black', 'Portland', 0, 0, 'In Production'),
('Black', 'Portland', 0, 0, 'Produced'),
('Black', 'Portland', 0, 0, 'In Stock'),
('Black', 'Phoenix', 0, 0, 'In Production'),
('Black', 'Phoenix', 0, 0, 'Produced'),
('Black', 'Phoenix', 0, 0, 'In Stock'),
('Black', 'Reno', 0, 0, 'In Production'),
('Black', 'Reno', 0, 0, 'Produced'),
('Black', 'Reno', 0, 0, 'In Stock'),
('Black', 'San Francisco New Mold', 0, 0, 'In Production'),
('Black', 'San Francisco New Mold', 0, 0, 'Produced'),
('Black', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Black', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Black', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Black', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Black', 'San Francisco ADA', 0, 0, 'In Production'),
('Black', 'San Francisco ADA', 0, 0, 'Produced'),
('Black', 'San Francisco ADA', 0, 0, 'In Stock'),
('Black', 'Mini San Francisco', 0, 0, 'In Production'),
('Black', 'Mini San Francisco', 0, 0, 'Produced'),
('Black', 'Mini San Francisco', 0, 0, 'In Stock'),
('Black', 'Seattle', 0, 0, 'In Production'),
('Black', 'Seattle', 0, 0, 'Produced'),
('Black', 'Seattle', 0, 0, 'In Stock'),
('Black', 'Texas', 0, 0, 'In Production'),
('Black', 'Texas', 0, 0, 'Produced'),
('Black', 'Texas', 0, 0, 'In Stock'),
('Black', 'Vegas 80', 0, 0, 'In Production'),
('Black', 'Vegas 80', 0, 0, 'Produced'),
('Black', 'Vegas 80', 0, 0, 'In Stock'),
('Black', 'Vegas 60', 0, 0, 'In Production'),
('Black', 'Vegas 60', 0, 0, 'Produced'),
('Black', 'Vegas 60', 0, 0, 'In Stock'),
('Black', 'Venice', 0, 0, 'In Production'),
('Black', 'Venice', 0, 0, 'Produced'),
('Black', 'Venice', 0, 0, 'In Stock'),
('Black', 'Washington', 0, 0, 'In Production'),
('Black', 'Washington', 0, 0, 'Produced'),
('Black', 'Washington', 0, 0, 'In Stock'),
('Black', 'Inner Planter', 0, 0, 'In Production'),
('Black', 'Inner Planter', 0, 0, 'Produced'),
('Black', 'Inner Planter', 0, 0, 'In Stock'),
('Black', 'Outer Planter', 0, 0, 'In Production'),
('Black', 'Outer Planter', 0, 0, 'Produced'),
('Black', 'Outer Planter', 0, 0, 'In Stock'),
('Blush', 'Atlanta', 0, 0, 'In Production'),
('Blush', 'Atlanta', 0, 0, 'Produced'),
('Blush', 'Atlanta', 0, 0, 'In Stock'),
('Blush', 'Boston', 0, 0, 'In Production'),
('Blush', 'Boston', 0, 0, 'Produced'),
('Blush', 'Boston', 0, 0, 'In Stock'),
('Blush', 'Carmel', 0, 0, 'In Production'),
('Blush', 'Carmel', 0, 0, 'Produced'),
('Blush', 'Carmel', 0, 0, 'In Stock'),
('Blush', 'Charleston', 0, 0, 'In Production'),
('Blush', 'Charleston', 0, 0, 'Produced'),
('Blush', 'Charleston', 0, 0, 'In Stock'),
('Blush', 'Chicago', 0, 0, 'In Production'),
('Blush', 'Chicago', 0, 0, 'Produced'),
('Blush', 'Chicago', 0, 0, 'In Stock'),
('Blush', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Blush', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Blush', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Blush', 'Denver', 0, 0, 'In Production'),
('Blush', 'Denver', 0, 0, 'Produced'),
('Blush', 'Denver', 0, 0, 'In Stock'),
('Blush', 'HD Round', 0, 0, 'In Production'),
('Blush', 'HD Round', 0, 0, 'Produced'),
('Blush', 'HD Round', 0, 0, 'In Stock'),
('Blush', 'Houston', 0, 0, 'In Production'),
('Blush', 'Houston', 0, 0, 'Produced'),
('Blush', 'Houston', 0, 0, 'In Stock'),
('Blush', 'Manhattan', 0, 0, 'In Production'),
('Blush', 'Manhattan', 0, 0, 'Produced'),
('Blush', 'Manhattan', 0, 0, 'In Stock'),
('Blush', 'Mini Manhattan', 0, 0, 'In Production'),
('Blush', 'Mini Manhattan', 0, 0, 'Produced'),
('Blush', 'Mini Manhattan', 0, 0, 'In Stock'),
('Blush', 'Miami', 0, 0, 'In Production'),
('Blush', 'Miami', 0, 0, 'Produced'),
('Blush', 'Miami', 0, 0, 'In Stock'),
('Blush', 'Mini Miami', 0, 0, 'In Production'),
('Blush', 'Mini Miami', 0, 0, 'Produced'),
('Blush', 'Mini Miami', 0, 0, 'In Stock'),
('Blush', 'Michu', 0, 0, 'In Production'),
('Blush', 'Michu', 0, 0, 'Produced'),
('Blush', 'Michu', 0, 0, 'In Stock'),
('Blush', 'Michu Planter', 0, 0, 'In Production'),
('Blush', 'Michu Planter', 0, 0, 'Produced'),
('Blush', 'Michu Planter', 0, 0, 'In Stock'),
('Blush', 'Minima', 0, 0, 'In Production'),
('Blush', 'Minima', 0, 0, 'Produced'),
('Blush', 'Minima', 0, 0, 'In Stock'),
('Blush', 'New York', 0, 0, 'In Production'),
('Blush', 'New York', 0, 0, 'Produced'),
('Blush', 'New York', 0, 0, 'In Stock'),
('Blush', 'New York 100', 0, 0, 'In Production'),
('Blush', 'New York 100', 0, 0, 'Produced'),
('Blush', 'New York 100', 0, 0, 'In Stock'),
('Blush', 'Orlando', 0, 0, 'In Production'),
('Blush', 'Orlando', 0, 0, 'Produced'),
('Blush', 'Orlando', 0, 0, 'In Stock'),
('Blush', 'Portland', 0, 0, 'In Production'),
('Blush', 'Portland', 0, 0, 'Produced'),
('Blush', 'Portland', 0, 0, 'In Stock'),
('Blush', 'Phoenix', 0, 0, 'In Production'),
('Blush', 'Phoenix', 0, 0, 'Produced'),
('Blush', 'Phoenix', 0, 0, 'In Stock'),
('Blush', 'Reno', 0, 0, 'In Production'),
('Blush', 'Reno', 0, 0, 'Produced'),
('Blush', 'Reno', 0, 0, 'In Stock'),
('Blush', 'San Francisco New Mold', 0, 0, 'In Production'),
('Blush', 'San Francisco New Mold', 0, 0, 'Produced'),
('Blush', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Blush', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Blush', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Blush', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Blush', 'San Francisco ADA', 0, 0, 'In Production'),
('Blush', 'San Francisco ADA', 0, 0, 'Produced'),
('Blush', 'San Francisco ADA', 0, 0, 'In Stock'), 
('Blush', 'Mini San Francisco', 0, 0, 'In Production'),
('Blush', 'Mini San Francisco', 0, 0, 'Produced'),
('Blush', 'Mini San Francisco', 0, 0, 'In Stock'),
('Blush', 'Seattle', 0, 0, 'In Production'),
('Blush', 'Seattle', 0, 0, 'Produced'),
('Blush', 'Seattle', 0, 0, 'In Stock'),
('Blush', 'Texas', 0, 0, 'In Production'),
('Blush', 'Texas', 0, 0, 'Produced'),
('Blush', 'Texas', 0, 0, 'In Stock'),
('Blush', 'Vegas 80', 0, 0, 'In Production'),
('Blush', 'Vegas 80', 0, 0, 'Produced'),
('Blush', 'Vegas 80', 0, 0, 'In Stock'),
('Blush', 'Vegas 60', 0, 0, 'In Production'),
('Blush', 'Vegas 60', 0, 0, 'Produced'),
('Blush', 'Vegas 60', 0, 0, 'In Stock'),
('Blush', 'Venice', 0, 0, 'In Production'),
('Blush', 'Venice', 0, 0, 'Produced'),
('Blush', 'Venice', 0, 0, 'In Stock'),
('Blush', 'Washington', 0, 0, 'In Production'),
('Blush', 'Washington', 0, 0, 'Produced'),
('Blush', 'Washington', 0, 0, 'In Stock'),
('Blush', 'Inner Planter', 0, 0, 'In Production'),
('Blush', 'Inner Planter', 0, 0, 'Produced'),
('Blush', 'Inner Planter', 0, 0, 'In Stock'),
('Blush', 'Outer Planter', 0, 0, 'In Production'),
('Blush', 'Outer Planter', 0, 0, 'Produced'),
('Blush', 'Outer Planter', 0, 0, 'In Stock'),
('Dark Blue', 'Atlanta', 0, 0, 'In Production'),
('Dark Blue', 'Atlanta', 0, 0, 'Produced'),
('Dark Blue', 'Atlanta', 0, 0, 'In Stock'),
('Dark Blue', 'Boston', 0, 0, 'In Production'),
('Dark Blue', 'Boston', 0, 0, 'Produced'),
('Dark Blue', 'Boston', 0, 0, 'In Stock'),
('Dark Blue', 'Carmel', 0, 0, 'In Production'),
('Dark Blue', 'Carmel', 0, 0, 'Produced'),
('Dark Blue', 'Carmel', 0, 0, 'In Stock'),
('Dark Blue', 'Charleston', 0, 0, 'In Production'),
('Dark Blue', 'Charleston', 0, 0, 'Produced'),
('Dark Blue', 'Charleston', 0, 0, 'In Stock'),
('Dark Blue', 'Chicago', 0, 0, 'In Production'),
('Dark Blue', 'Chicago', 0, 0, 'Produced'),
('Dark Blue', 'Chicago', 0, 0, 'In Stock'),
('Dark Blue', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Dark Blue', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Dark Blue', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Dark Blue', 'Denver', 0, 0, 'In Production'),
('Dark Blue', 'Denver', 0, 0, 'Produced'),
('Dark Blue', 'Denver', 0, 0, 'In Stock'),
('Dark Blue', 'HD Round', 0, 0, 'In Production'),
('Dark Blue', 'HD Round', 0, 0, 'Produced'),
('Dark Blue', 'HD Round', 0, 0, 'In Stock'),
('Dark Blue', 'Houston', 0, 0, 'In Production'),
('Dark Blue', 'Houston', 0, 0, 'Produced'),
('Dark Blue', 'Houston', 0, 0, 'In Stock'),
('Dark Blue', 'Manhattan', 0, 0, 'In Production'),
('Dark Blue', 'Manhattan', 0, 0, 'Produced'),
('Dark Blue', 'Manhattan', 0, 0, 'In Stock'),
('Dark Blue', 'Mini Manhattan', 0, 0, 'In Production'),
('Dark Blue', 'Mini Manhattan', 0, 0, 'Produced'),
('Dark Blue', 'Mini Manhattan', 0, 0, 'In Stock'),
('Dark Blue', 'Miami', 0, 0, 'In Production'),
('Dark Blue', 'Miami', 0, 0, 'Produced'),
('Dark Blue', 'Miami', 0, 0, 'In Stock'),
('Dark Blue', 'Mini Miami', 0, 0, 'In Production'),
('Dark Blue', 'Mini Miami', 0, 0, 'Produced'),
('Dark Blue', 'Mini Miami', 0, 0, 'In Stock'),
('Dark Blue', 'Michu', 0, 0, 'In Production'),
('Dark Blue', 'Michu', 0, 0, 'Produced'),
('Dark Blue', 'Michu', 0, 0, 'In Stock'),
('Dark Blue', 'Michu Planter', 0, 0, 'In Production'),
('Dark Blue', 'Michu Planter', 0, 0, 'Produced'),
('Dark Blue', 'Michu Planter', 0, 0, 'In Stock'),
('Dark Blue', 'Minima', 0, 0, 'In Production'),
('Dark Blue', 'Minima', 0, 0, 'Produced'),
('Dark Blue', 'Minima', 0, 0, 'In Stock'),
('Dark Blue', 'New York', 0, 0, 'In Production'),
('Dark Blue', 'New York', 0, 0, 'Produced'),
('Dark Blue', 'New York', 0, 0, 'In Stock'),
('Dark Blue', 'New York 100', 0, 0, 'In Production'),
('Dark Blue', 'New York 100', 0, 0, 'Produced'),
('Dark Blue', 'New York 100', 0, 0, 'In Stock'),
('Dark Blue', 'Orlando', 0, 0, 'In Production'),
('Dark Blue', 'Orlando', 0, 0, 'Produced'),
('Dark Blue', 'Orlando', 0, 0, 'In Stock'),
('Dark Blue', 'Portland', 0, 0, 'In Production'),
('Dark Blue', 'Portland', 0, 0, 'Produced'),
('Dark Blue', 'Portland', 0, 0, 'In Stock'),
('Dark Blue', 'Phoenix', 0, 0, 'In Production'),
('Dark Blue', 'Phoenix', 0, 0, 'Produced'),
('Dark Blue', 'Phoenix', 0, 0, 'In Stock'),
('Dark Blue', 'Reno', 0, 0, 'In Production'),
('Dark Blue', 'Reno', 0, 0, 'Produced'),
('Dark Blue', 'Reno', 0, 0, 'In Stock'),
('Dark Blue', 'San Francisco New Mold', 0, 0, 'In Production'),
('Dark Blue', 'San Francisco New Mold', 0, 0, 'Produced'),
('Dark Blue', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Dark Blue', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Dark Blue', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Dark Blue', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Dark Blue', 'San Francisco ADA', 0, 0, 'In Production'),
('Dark Blue', 'San Francisco ADA', 0, 0, 'Produced'),
('Dark Blue', 'San Francisco ADA', 0, 0, 'In Stock'),
('Dark Blue', 'Mini San Francisco', 0, 0, 'In Production'),
('Dark Blue', 'Mini San Francisco', 0, 0, 'Produced'),
('Dark Blue', 'Mini San Francisco', 0, 0, 'In Stock'),
('Dark Blue', 'Seattle', 0, 0, 'In Production'),
('Dark Blue', 'Seattle', 0, 0, 'Produced'),
('Dark Blue', 'Seattle', 0, 0, 'In Stock'),
('Dark Blue', 'Texas', 0, 0, 'In Production'),
('Dark Blue', 'Texas', 0, 0, 'Produced'),
('Dark Blue', 'Texas', 0, 0, 'In Stock'),
('Dark Blue', 'Vegas 80', 0, 0, 'In Production'),
('Dark Blue', 'Vegas 80', 0, 0, 'Produced'),
('Dark Blue', 'Vegas 80', 0, 0, 'In Stock'),
('Dark Blue', 'Vegas 60', 0, 0, 'In Production'),
('Dark Blue', 'Vegas 60', 0, 0, 'Produced'),
('Dark Blue', 'Vegas 60', 0, 0, 'In Stock'),
('Dark Blue', 'Venice', 0, 0, 'In Production'),
('Dark Blue', 'Venice', 0, 0, 'Produced'),
('Dark Blue', 'Venice', 0, 0, 'In Stock'),
('Dark Blue', 'Washington', 0, 0, 'In Production'),
('Dark Blue', 'Washington', 0, 0, 'Produced'),
('Dark Blue', 'Washington', 0, 0, 'In Stock'),
('Dark Blue', 'Inner Planter', 0, 0, 'In Production'),
('Dark Blue', 'Inner Planter', 0, 0, 'Produced'),
('Dark Blue', 'Inner Planter', 0, 0, 'In Stock'),
('Dark Blue', 'Outer Planter', 0, 0, 'In Production'),
('Dark Blue', 'Outer Planter', 0, 0, 'Produced'),
('Dark Blue', 'Outer Planter', 0, 0, 'In Stock'),
('Light Blue', 'Atlanta', 0, 0, 'In Production'),
('Light Blue', 'Atlanta', 0, 0, 'Produced'),
('Light Blue', 'Atlanta', 0, 0, 'In Stock'),
('Light Blue', 'Boston', 0, 0, 'In Production'),
('Light Blue', 'Boston', 0, 0, 'Produced'),
('Light Blue', 'Boston', 0, 0, 'In Stock'),
('Light Blue', 'Carmel', 0, 0, 'In Production'),
('Light Blue', 'Carmel', 0, 0, 'Produced'),
('Light Blue', 'Carmel', 0, 0, 'In Stock'),
('Light Blue', 'Charleston', 0, 0, 'In Production'),
('Light Blue', 'Charleston', 0, 0, 'Produced'),
('Light Blue', 'Charleston', 0, 0, 'In Stock'),
('Light Blue', 'Chicago', 0, 0, 'In Production'),
('Light Blue', 'Chicago', 0, 0, 'Produced'),
('Light Blue', 'Chicago', 0, 0, 'In Stock'),
('Light Blue', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Light Blue', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Light Blue', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Light Blue', 'Denver', 0, 0, 'In Production'),
('Light Blue', 'Denver', 0, 0, 'Produced'),
('Light Blue', 'Denver', 0, 0, 'In Stock'),
('Light Blue', 'HD Round', 0, 0, 'In Production'),
('Light Blue', 'HD Round', 0, 0, 'Produced'),
('Light Blue', 'HD Round', 0, 0, 'In Stock'),
('Light Blue', 'Houston', 0, 0, 'In Production'),
('Light Blue', 'Houston', 0, 0, 'Produced'),
('Light Blue', 'Houston', 0, 0, 'In Stock'),
('Light Blue', 'Manhattan', 0, 0, 'In Production'),
('Light Blue', 'Manhattan', 0, 0, 'Produced'),
('Light Blue', 'Manhattan', 0, 0, 'In Stock'),
('Light Blue', 'Mini Manhattan', 0, 0, 'In Production'),
('Light Blue', 'Mini Manhattan', 0, 0, 'Produced'),
('Light Blue', 'Mini Manhattan', 0, 0, 'In Stock'),
('Light Blue', 'Miami', 0, 0, 'In Production'),
('Light Blue', 'Miami', 0, 0, 'Produced'), 
('Light Blue', 'Miami', 0, 0, 'In Stock'),
('Light Blue', 'Mini Miami', 0, 0, 'In Production'),
('Light Blue', 'Mini Miami', 0, 0, 'Produced'),
('Light Blue', 'Mini Miami', 0, 0, 'In Stock'),
('Light Blue', 'Michu', 0, 0, 'In Production'),
('Light Blue', 'Michu', 0, 0, 'Produced'),
('Light Blue', 'Michu', 0, 0, 'In Stock'),
('Light Blue', 'Michu Planter', 0, 0, 'In Production'),
('Light Blue', 'Michu Planter', 0, 0, 'Produced'),
('Light Blue', 'Michu Planter', 0, 0, 'In Stock'),
('Light Blue', 'Minima', 0, 0, 'In Production'),
('Light Blue', 'Minima', 0, 0, 'Produced'),
('Light Blue', 'Minima', 0, 0, 'In Stock'),
('Light Blue', 'New York', 0, 0, 'In Production'),
('Light Blue', 'New York', 0, 0, 'Produced'),
('Light Blue', 'New York', 0, 0, 'In Stock'),
('Light Blue', 'New York 100', 0, 0, 'In Production'),
('Light Blue', 'New York 100', 0, 0, 'Produced'),
('Light Blue', 'New York 100', 0, 0, 'In Stock'),
('Light Blue', 'Orlando', 0, 0, 'In Production'),
('Light Blue', 'Orlando', 0, 0, 'Produced'),
('Light Blue', 'Orlando', 0, 0, 'In Stock'),
('Light Blue', 'Portland', 0, 0, 'In Production'),
('Light Blue', 'Portland', 0, 0, 'Produced'),
('Light Blue', 'Portland', 0, 0, 'In Stock'),
('Light Blue', 'Phoenix', 0, 0, 'In Production'),
('Light Blue', 'Phoenix', 0, 0, 'Produced'),
('Light Blue', 'Phoenix', 0, 0, 'In Stock'),
('Light Blue', 'Reno', 0, 0, 'In Production'),
('Light Blue', 'Reno', 0, 0, 'Produced'),
('Light Blue', 'Reno', 0, 0, 'In Stock'),
('Light Blue', 'San Francisco New Mold', 0, 0, 'In Production'),
('Light Blue', 'San Francisco New Mold', 0, 0, 'Produced'),
('Light Blue', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Light Blue', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Light Blue', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Light Blue', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Light Blue', 'San Francisco ADA', 0, 0, 'In Production'),
('Light Blue', 'San Francisco ADA', 0, 0, 'Produced'),
('Light Blue', 'San Francisco ADA', 0, 0, 'In Stock'),
('Light Blue', 'Mini San Francisco', 0, 0, 'In Production'),
('Light Blue', 'Mini San Francisco', 0, 0, 'Produced'),
('Light Blue', 'Mini San Francisco', 0, 0, 'In Stock'),
('Light Blue', 'Seattle', 0, 0, 'In Production'),
('Light Blue', 'Seattle', 0, 0, 'Produced'),
('Light Blue', 'Seattle', 0, 0, 'In Stock'),
('Light Blue', 'Texas', 0, 0, 'In Production'),
('Light Blue', 'Texas', 0, 0, 'Produced'),
('Light Blue', 'Texas', 0, 0, 'In Stock'),
('Light Blue', 'Vegas 80', 0, 0, 'In Production'),
('Light Blue', 'Vegas 80', 0, 0, 'Produced'),
('Light Blue', 'Vegas 80', 0, 0, 'In Stock'),
('Light Blue', 'Vegas 60', 0, 0, 'In Production'),
('Light Blue', 'Vegas 60', 0, 0, 'Produced'),
('Light Blue', 'Vegas 60', 0, 0, 'In Stock'),
('Light Blue', 'Venice', 0, 0, 'In Production'),
('Light Blue', 'Venice', 0, 0, 'Produced'),
('Light Blue', 'Venice', 0, 0, 'In Stock'),
('Light Blue', 'Washington', 0, 0, 'In Production'),
('Light Blue', 'Washington', 0, 0, 'Produced'),
('Light Blue', 'Washington', 0, 0, 'In Stock'),
('Light Blue', 'Inner Planter', 0, 0, 'In Production'),
('Light Blue', 'Inner Planter', 0, 0, 'Produced'),
('Light Blue', 'Inner Planter', 0, 0, 'In Stock'),
('Light Blue', 'Outer Planter', 0, 0, 'In Production'),
('Light Blue', 'Outer Planter', 0, 0, 'Produced'),
('Light Blue', 'Outer Planter', 0, 0, 'In Stock'),
('Eggplant', 'Atlanta', 0, 0, 'In Production'),
('Eggplant', 'Atlanta', 0, 0, 'Produced'),
('Eggplant', 'Atlanta', 0, 0, 'In Stock'),
('Eggplant', 'Boston', 0, 0, 'In Production'),
('Eggplant', 'Boston', 0, 0, 'Produced'),
('Eggplant', 'Boston', 0, 0, 'In Stock'),
('Eggplant', 'Carmel', 0, 0, 'In Production'),
('Eggplant', 'Carmel', 0, 0, 'Produced'),
('Eggplant', 'Carmel', 0, 0, 'In Stock'),
('Eggplant', 'Charleston', 0, 0, 'In Production'),
('Eggplant', 'Charleston', 0, 0, 'Produced'),
('Eggplant', 'Charleston', 0, 0, 'In Stock'),
('Eggplant', 'Chicago', 0, 0, 'In Production'),
('Eggplant', 'Chicago', 0, 0, 'Produced'),
('Eggplant', 'Chicago', 0, 0, 'In Stock'),
('Eggplant', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Eggplant', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Eggplant', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Eggplant', 'Denver', 0, 0, 'In Production'),
('Eggplant', 'Denver', 0, 0, 'Produced'),
('Eggplant', 'Denver', 0, 0, 'In Stock'),
('Eggplant', 'HD Round', 0, 0, 'In Production'),
('Eggplant', 'HD Round', 0, 0, 'Produced'),
('Eggplant', 'HD Round', 0, 0, 'In Stock'),
('Eggplant', 'Houston', 0, 0, 'In Production'),
('Eggplant', 'Houston', 0, 0, 'Produced'),
('Eggplant', 'Houston', 0, 0, 'In Stock'),
('Eggplant', 'Manhattan', 0, 0, 'In Production'),
('Eggplant', 'Manhattan', 0, 0, 'Produced'),
('Eggplant', 'Manhattan', 0, 0, 'In Stock'),
('Eggplant', 'Mini Manhattan', 0, 0, 'In Production'),
('Eggplant', 'Mini Manhattan', 0, 0, 'Produced'),
('Eggplant', 'Mini Manhattan', 0, 0, 'In Stock'),
('Eggplant', 'Miami', 0, 0, 'In Production'),
('Eggplant', 'Miami', 0, 0, 'Produced'),
('Eggplant', 'Miami', 0, 0, 'In Stock'),
('Eggplant', 'Mini Miami', 0, 0, 'In Production'),
('Eggplant', 'Mini Miami', 0, 0, 'Produced'),
('Eggplant', 'Mini Miami', 0, 0, 'In Stock'),
('Eggplant', 'Michu', 0, 0, 'In Production'),
('Eggplant', 'Michu', 0, 0, 'Produced'),
('Eggplant', 'Michu', 0, 0, 'In Stock'),
('Eggplant', 'Michu Planter', 0, 0, 'In Production'),
('Eggplant', 'Michu Planter', 0, 0, 'Produced'),
('Eggplant', 'Michu Planter', 0, 0, 'In Stock'),
('Eggplant', 'Minima', 0, 0, 'In Production'),
('Eggplant', 'Minima', 0, 0, 'Produced'),
('Eggplant', 'Minima', 0, 0, 'In Stock'),
('Eggplant', 'New York', 0, 0, 'In Production'),
('Eggplant', 'New York', 0, 0, 'Produced'),
('Eggplant', 'New York', 0, 0, 'In Stock'),
('Eggplant', 'New York 100', 0, 0, 'In Production'),
('Eggplant', 'New York 100', 0, 0, 'Produced'),
('Eggplant', 'New York 100', 0, 0, 'In Stock'),
('Eggplant', 'Orlando', 0, 0, 'In Production'),
('Eggplant', 'Orlando', 0, 0, 'Produced'),
('Eggplant', 'Orlando', 0, 0, 'In Stock'),
('Eggplant', 'Portland', 0, 0, 'In Production'),
('Eggplant', 'Portland', 0, 0, 'Produced'),
('Eggplant', 'Portland', 0, 0, 'In Stock'),
('Eggplant', 'Phoenix', 0, 0, 'In Production'),
('Eggplant', 'Phoenix', 0, 0, 'Produced'),
('Eggplant', 'Phoenix', 0, 0, 'In Stock'),
('Eggplant', 'Reno', 0, 0, 'In Production'),
('Eggplant', 'Reno', 0, 0, 'Produced'),
('Eggplant', 'Reno', 0, 0, 'In Stock'),
('Eggplant', 'San Francisco New Mold', 0, 0, 'In Production'),
('Eggplant', 'San Francisco New Mold', 0, 0, 'Produced'),
('Eggplant', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Eggplant', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Eggplant', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Eggplant', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Eggplant', 'San Francisco ADA', 0, 0, 'In Production'),
('Eggplant', 'San Francisco ADA', 0, 0, 'Produced'),
('Eggplant', 'San Francisco ADA', 0, 0, 'In Stock'),
('Eggplant', 'Mini San Francisco', 0, 0, 'In Production'),
('Eggplant', 'Mini San Francisco', 0, 0, 'Produced'),
('Eggplant', 'Mini San Francisco', 0, 0, 'In Stock'),
('Eggplant', 'Seattle', 0, 0, 'In Production'),
('Eggplant', 'Seattle', 0, 0, 'Produced'),
('Eggplant', 'Seattle', 0, 0, 'In Stock'),
('Eggplant', 'Texas', 0, 0, 'In Production'),
('Eggplant', 'Texas', 0, 0, 'Produced'),
('Eggplant', 'Texas', 0, 0, 'In Stock'),
('Eggplant', 'Vegas 80', 0, 0, 'In Production'),
('Eggplant', 'Vegas 80', 0, 0, 'Produced'),
('Eggplant', 'Vegas 80', 0, 0, 'In Stock'),
('Eggplant', 'Vegas 60', 0, 0, 'In Production'),
('Eggplant', 'Vegas 60', 0, 0, 'Produced'),
('Eggplant', 'Vegas 60', 0, 0, 'In Stock'),
('Eggplant', 'Venice', 0, 0, 'In Production'),
('Eggplant', 'Venice', 0, 0, 'Produced'),
('Eggplant', 'Venice', 0, 0, 'In Stock'),
('Eggplant', 'Washington', 0, 0, 'In Production'),
('Eggplant', 'Washington', 0, 0, 'Produced'), 
('Eggplant', 'Washington', 0, 0, 'In Stock'),
('Eggplant', 'Inner Planter', 0, 0, 'In Production'),
('Eggplant', 'Inner Planter', 0, 0, 'Produced'),
('Eggplant', 'Inner Planter', 0, 0, 'In Stock'),
('Eggplant', 'Outer Planter', 0, 0, 'In Production'),
('Eggplant', 'Outer Planter', 0, 0, 'Produced'),
('Eggplant', 'Outer Planter', 0, 0, 'In Stock'),
('Kale', 'Atlanta', 0, 0, 'In Production'),
('Kale', 'Atlanta', 0, 0, 'Produced'),
('Kale', 'Atlanta', 0, 0, 'In Stock'),
('Kale', 'Boston', 0, 0, 'In Production'),
('Kale', 'Boston', 0, 0, 'Produced'),
('Kale', 'Boston', 0, 0, 'In Stock'),
('Kale', 'Carmel', 0, 0, 'In Production'),
('Kale', 'Carmel', 0, 0, 'Produced'),
('Kale', 'Carmel', 0, 0, 'In Stock'),
('Kale', 'Charleston', 0, 0, 'In Production'),
('Kale', 'Charleston', 0, 0, 'Produced'),
('Kale', 'Charleston', 0, 0, 'In Stock'),
('Kale', 'Chicago', 0, 0, 'In Production'),
('Kale', 'Chicago', 0, 0, 'Produced'),
('Kale', 'Chicago', 0, 0, 'In Stock'),
('Kale', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Kale', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Kale', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Kale', 'Denver', 0, 0, 'In Production'),
('Kale', 'Denver', 0, 0, 'Produced'),
('Kale', 'Denver', 0, 0, 'In Stock'),
('Kale', 'HD Round', 0, 0, 'In Production'),
('Kale', 'HD Round', 0, 0, 'Produced'),
('Kale', 'HD Round', 0, 0, 'In Stock'),
('Kale', 'Houston', 0, 0, 'In Production'),
('Kale', 'Houston', 0, 0, 'Produced'),
('Kale', 'Houston', 0, 0, 'In Stock'),
('Kale', 'Manhattan', 0, 0, 'In Production'),
('Kale', 'Manhattan', 0, 0, 'Produced'),
('Kale', 'Manhattan', 0, 0, 'In Stock'),
('Kale', 'Mini Manhattan', 0, 0, 'In Production'),
('Kale', 'Mini Manhattan', 0, 0, 'Produced'),
('Kale', 'Mini Manhattan', 0, 0, 'In Stock'),
('Kale', 'Miami', 0, 0, 'In Production'),
('Kale', 'Miami', 0, 0, 'Produced'),
('Kale', 'Miami', 0, 0, 'In Stock'),
('Kale', 'Mini Miami', 0, 0, 'In Production'),
('Kale', 'Mini Miami', 0, 0, 'Produced'),
('Kale', 'Mini Miami', 0, 0, 'In Stock'),
('Kale', 'Michu', 0, 0, 'In Production'),
('Kale', 'Michu', 0, 0, 'Produced'),
('Kale', 'Michu', 0, 0, 'In Stock'),
('Kale', 'Michu Planter', 0, 0, 'In Production'),
('Kale', 'Michu Planter', 0, 0, 'Produced'),
('Kale', 'Michu Planter', 0, 0, 'In Stock'),
('Kale', 'Minima', 0, 0, 'In Production'),
('Kale', 'Minima', 0, 0, 'Produced'),
('Kale', 'Minima', 0, 0, 'In Stock'),
('Kale', 'New York', 0, 0, 'In Production'),
('Kale', 'New York', 0, 0, 'Produced'),
('Kale', 'New York', 0, 0, 'In Stock'),
('Kale', 'New York 100', 0, 0, 'In Production'),
('Kale', 'New York 100', 0, 0, 'Produced'),
('Kale', 'New York 100', 0, 0, 'In Stock'),
('Kale', 'Orlando', 0, 0, 'In Production'),
('Kale', 'Orlando', 0, 0, 'Produced'),
('Kale', 'Orlando', 0, 0, 'In Stock'),
('Kale', 'Portland', 0, 0, 'In Production'),
('Kale', 'Portland', 0, 0, 'Produced'),
('Kale', 'Portland', 0, 0, 'In Stock'),
('Kale', 'Phoenix', 0, 0, 'In Production'),
('Kale', 'Phoenix', 0, 0, 'Produced'),
('Kale', 'Phoenix', 0, 0, 'In Stock'),
('Kale', 'Reno', 0, 0, 'In Production'),
('Kale', 'Reno', 0, 0, 'Produced'),
('Kale', 'Reno', 0, 0, 'In Stock'),
('Kale', 'San Francisco New Mold', 0, 0, 'In Production'),
('Kale', 'San Francisco New Mold', 0, 0, 'Produced'),
('Kale', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Kale', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Kale', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Kale', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Kale', 'San Francisco ADA', 0, 0, 'In Production'),
('Kale', 'San Francisco ADA', 0, 0, 'Produced'),
('Kale', 'San Francisco ADA', 0, 0, 'In Stock'),
('Kale', 'Mini San Francisco', 0, 0, 'In Production'),
('Kale', 'Mini San Francisco', 0, 0, 'Produced'),
('Kale', 'Mini San Francisco', 0, 0, 'In Stock'),
('Kale', 'Seattle', 0, 0, 'In Production'),
('Kale', 'Seattle', 0, 0, 'Produced'),
('Kale', 'Seattle', 0, 0, 'In Stock'),
('Kale', 'Texas', 0, 0, 'In Production'),
('Kale', 'Texas', 0, 0, 'Produced'),
('Kale', 'Texas', 0, 0, 'In Stock'),
('Kale', 'Vegas 80', 0, 0, 'In Production'),
('Kale', 'Vegas 80', 0, 0, 'Produced'),
('Kale', 'Vegas 80', 0, 0, 'In Stock'),
('Kale', 'Vegas 60', 0, 0, 'In Production'),
('Kale', 'Vegas 60', 0, 0, 'Produced'),
('Kale', 'Vegas 60', 0, 0, 'In Stock'),
('Kale', 'Venice', 0, 0, 'In Production'),
('Kale', 'Venice', 0, 0, 'Produced'),
('Kale', 'Venice', 0, 0, 'In Stock'),
('Kale', 'Washington', 0, 0, 'In Production'),
('Kale', 'Washington', 0, 0, 'Produced'),
('Kale', 'Washington', 0, 0, 'In Stock'),
('Kale', 'Inner Planter', 0, 0, 'In Production'),
('Kale', 'Inner Planter', 0, 0, 'Produced'),
('Kale', 'Inner Planter', 0, 0, 'In Stock'),
('Kale', 'Outer Planter', 0, 0, 'In Production'),
('Kale', 'Outer Planter', 0, 0, 'Produced'),
('Kale', 'Outer Planter', 0, 0, 'In Stock'),
('Lavender', 'Atlanta', 0, 0, 'In Production'),
('Lavender', 'Atlanta', 0, 0, 'Produced'),
('Lavender', 'Atlanta', 0, 0, 'In Stock'),
('Lavender', 'Boston', 0, 0, 'In Production'),
('Lavender', 'Boston', 0, 0, 'Produced'),
('Lavender', 'Boston', 0, 0, 'In Stock'),
('Lavender', 'Carmel', 0, 0, 'In Production'),
('Lavender', 'Carmel', 0, 0, 'Produced'),
('Lavender', 'Carmel', 0, 0, 'In Stock'),
('Lavender', 'Charleston', 0, 0, 'In Production'),
('Lavender', 'Charleston', 0, 0, 'Produced'),
('Lavender', 'Charleston', 0, 0, 'In Stock'),
('Lavender', 'Chicago', 0, 0, 'In Production'),
('Lavender', 'Chicago', 0, 0, 'Produced'),
('Lavender', 'Chicago', 0, 0, 'In Stock'),
('Lavender', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Lavender', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Lavender', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Lavender', 'Denver', 0, 0, 'In Production'),
('Lavender', 'Denver', 0, 0, 'Produced'),
('Lavender', 'Denver', 0, 0, 'In Stock'),
('Lavender', 'HD Round', 0, 0, 'In Production'),
('Lavender', 'HD Round', 0, 0, 'Produced'),
('Lavender', 'HD Round', 0, 0, 'In Stock'),
('Lavender', 'Houston', 0, 0, 'In Production'),
('Lavender', 'Houston', 0, 0, 'Produced'),
('Lavender', 'Houston', 0, 0, 'In Stock'),
('Lavender', 'Manhattan', 0, 0, 'In Production'),
('Lavender', 'Manhattan', 0, 0, 'Produced'),
('Lavender', 'Manhattan', 0, 0, 'In Stock'),
('Lavender', 'Mini Manhattan', 0, 0, 'In Production'),
('Lavender', 'Mini Manhattan', 0, 0, 'Produced'),
('Lavender', 'Mini Manhattan', 0, 0, 'In Stock'),
('Lavender', 'Miami', 0, 0, 'In Production'),
('Lavender', 'Miami', 0, 0, 'Produced'),
('Lavender', 'Miami', 0, 0, 'In Stock'),
('Lavender', 'Mini Miami', 0, 0, 'In Production'),
('Lavender', 'Mini Miami', 0, 0, 'Produced'),
('Lavender', 'Mini Miami', 0, 0, 'In Stock'),
('Lavender', 'Michu', 0, 0, 'In Production'),
('Lavender', 'Michu', 0, 0, 'Produced'),
('Lavender', 'Michu', 0, 0, 'In Stock'),
('Lavender', 'Michu Planter', 0, 0, 'In Production'),
('Lavender', 'Michu Planter', 0, 0, 'Produced'),
('Lavender', 'Michu Planter', 0, 0, 'In Stock'),
('Lavender', 'Minima', 0, 0, 'In Production'),
('Lavender', 'Minima', 0, 0, 'Produced'),
('Lavender', 'Minima', 0, 0, 'In Stock'),
('Lavender', 'New York', 0, 0, 'In Production'),
('Lavender', 'New York', 0, 0, 'Produced'),
('Lavender', 'New York', 0, 0, 'In Stock'),
('Lavender', 'New York 100', 0, 0, 'In Production'),
('Lavender', 'New York 100', 0, 0, 'Produced'),
('Lavender', 'New York 100', 0, 0, 'In Stock'),
('Lavender', 'Orlando', 0, 0, 'In Production'),
('Lavender', 'Orlando', 0, 0, 'Produced'),
('Lavender', 'Orlando', 0, 0, 'In Stock'),
('Lavender', 'Portland', 0, 0, 'In Production'),
('Lavender', 'Portland', 0, 0, 'Produced'),
('Lavender', 'Portland', 0, 0, 'In Stock'),
('Lavender', 'Phoenix', 0, 0, 'In Production'),
('Lavender', 'Phoenix', 0, 0, 'Produced'),
('Lavender', 'Phoenix', 0, 0, 'In Stock'),
('Lavender', 'Reno', 0, 0, 'In Production'),
('Lavender', 'Reno', 0, 0, 'Produced'),
('Lavender', 'Reno', 0, 0, 'In Stock'),
('Lavender', 'San Francisco New Mold', 0, 0, 'In Production'),
('Lavender', 'San Francisco New Mold', 0, 0, 'Produced'),
('Lavender', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Lavender', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Lavender', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Lavender', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Lavender', 'San Francisco ADA', 0, 0, 'In Production'),
('Lavender', 'San Francisco ADA', 0, 0, 'Produced'),
('Lavender', 'San Francisco ADA', 0, 0, 'In Stock'),
('Lavender', 'Mini San Francisco', 0, 0, 'In Production'),
('Lavender', 'Mini San Francisco', 0, 0, 'Produced'),
('Lavender', 'Mini San Francisco', 0, 0, 'In Stock'),
('Lavender', 'Seattle', 0, 0, 'In Production'),
('Lavender', 'Seattle', 0, 0, 'Produced'),
('Lavender', 'Seattle', 0, 0, 'In Stock'),
('Lavender', 'Texas', 0, 0, 'In Production'),
('Lavender', 'Texas', 0, 0, 'Produced'),
('Lavender', 'Texas', 0, 0, 'In Stock'),
('Lavender', 'Vegas 80', 0, 0, 'In Production'),
('Lavender', 'Vegas 80', 0, 0, 'Produced'),
('Lavender', 'Vegas 80', 0, 0, 'In Stock'),
('Lavender', 'Vegas 60', 0, 0, 'In Production'),
('Lavender', 'Vegas 60', 0, 0, 'Produced'),
('Lavender', 'Vegas 60', 0, 0, 'In Stock'),
('Lavender', 'Venice', 0, 0, 'In Production'),
('Lavender', 'Venice', 0, 0, 'Produced'),
('Lavender', 'Venice', 0, 0, 'In Stock'),
('Lavender', 'Washington', 0, 0, 'In Production'),
('Lavender', 'Washington', 0, 0, 'Produced'),
('Lavender', 'Washington', 0, 0, 'In Stock'),
('Lavender', 'Inner Planter', 0, 0, 'In Production'),
('Lavender', 'Inner Planter', 0, 0, 'Produced'),
('Lavender', 'Inner Planter', 0, 0, 'In Stock'),
('Lavender', 'Outer Planter', 0, 0, 'In Production'),
('Lavender', 'Outer Planter', 0, 0, 'Produced'),
('Lavender', 'Outer Planter', 0, 0, 'In Stock'),
('Licorice', 'Atlanta', 0, 0, 'In Production'),
('Licorice', 'Atlanta', 0, 0, 'Produced'),
('Licorice', 'Atlanta', 0, 0, 'In Stock'),
('Licorice', 'Boston', 0, 0, 'In Production'),
('Licorice', 'Boston', 0, 0, 'Produced'),
('Licorice', 'Boston', 0, 0, 'In Stock'),
('Licorice', 'Carmel', 0, 0, 'In Production'),
('Licorice', 'Carmel', 0, 0, 'Produced'),
('Licorice', 'Carmel', 0, 0, 'In Stock'),
('Licorice', 'Charleston', 0, 0, 'In Production'),
('Licorice', 'Charleston', 0, 0, 'Produced'),
('Licorice', 'Charleston', 0, 0, 'In Stock'),
('Licorice', 'Chicago', 0, 0, 'In Production'),
('Licorice', 'Chicago', 0, 0, 'Produced'),
('Licorice', 'Chicago', 0, 0, 'In Stock'),
('Licorice', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Licorice', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Licorice', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Licorice', 'Denver', 0, 0, 'In Production'),
('Licorice', 'Denver', 0, 0, 'Produced'),
('Licorice', 'Denver', 0, 0, 'In Stock'),
('Licorice', 'HD Round', 0, 0, 'In Production'),
('Licorice', 'HD Round', 0, 0, 'Produced'),
('Licorice', 'HD Round', 0, 0, 'In Stock'),
('Licorice', 'Houston', 0, 0, 'In Production'),
('Licorice', 'Houston', 0, 0, 'Produced'),
('Licorice', 'Houston', 0, 0, 'In Stock'),
('Licorice', 'Manhattan', 0, 0, 'In Production'),
('Licorice', 'Manhattan', 0, 0, 'Produced'),
('Licorice', 'Manhattan', 0, 0, 'In Stock'),
('Licorice', 'Mini Manhattan', 0, 0, 'In Production'),
('Licorice', 'Mini Manhattan', 0, 0, 'Produced'),
('Licorice', 'Mini Manhattan', 0, 0, 'In Stock'),
('Licorice', 'Miami', 0, 0, 'In Production'),
('Licorice', 'Miami', 0, 0, 'Produced'),
('Licorice', 'Miami', 0, 0, 'In Stock'),
('Licorice', 'Mini Miami', 0, 0, 'In Production'),
('Licorice', 'Mini Miami', 0, 0, 'Produced'),
('Licorice', 'Mini Miami', 0, 0, 'In Stock'),
('Licorice', 'Michu', 0, 0, 'In Production'),
('Licorice', 'Michu', 0, 0, 'Produced'),
('Licorice', 'Michu', 0, 0, 'In Stock'),
('Licorice', 'Michu Planter', 0, 0, 'In Production'),
('Licorice', 'Michu Planter', 0, 0, 'Produced'),
('Licorice', 'Michu Planter', 0, 0, 'In Stock'),
('Licorice', 'Minima', 0, 0, 'In Production'),
('Licorice', 'Minima', 0, 0, 'Produced'),
('Licorice', 'Minima', 0, 0, 'In Stock'),
('Licorice', 'New York', 0, 0, 'In Production'),
('Licorice', 'New York', 0, 0, 'Produced'),
('Licorice', 'New York', 0, 0, 'In Stock'),
('Licorice', 'New York 100', 0, 0, 'In Production'),
('Licorice', 'New York 100', 0, 0, 'Produced'),
('Licorice', 'New York 100', 0, 0, 'In Stock'),
('Licorice', 'Orlando', 0, 0, 'In Production'),
('Licorice', 'Orlando', 0, 0, 'Produced'),
('Licorice', 'Orlando', 0, 0, 'In Stock'),
('Licorice', 'Portland', 0, 0, 'In Production'),
('Licorice', 'Portland', 0, 0, 'Produced'),
('Licorice', 'Portland', 0, 0, 'In Stock'),
('Licorice', 'Phoenix', 0, 0, 'In Production'),
('Licorice', 'Phoenix', 0, 0, 'Produced'),
('Licorice', 'Phoenix', 0, 0, 'In Stock'),
('Licorice', 'Reno', 0, 0, 'In Production'),
('Licorice', 'Reno', 0, 0, 'Produced'),
('Licorice', 'Reno', 0, 0, 'In Stock'),
('Licorice', 'San Francisco New Mold', 0, 0, 'In Production'),
('Licorice', 'San Francisco New Mold', 0, 0, 'Produced'),
('Licorice', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Licorice', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Licorice', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Licorice', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Licorice', 'San Francisco ADA', 0, 0, 'In Production'),
('Licorice', 'San Francisco ADA', 0, 0, 'Produced'),
('Licorice', 'San Francisco ADA', 0, 0, 'In Stock'),
('Licorice', 'Mini San Francisco', 0, 0, 'In Production'),
('Licorice', 'Mini San Francisco', 0, 0, 'Produced'),
('Licorice', 'Mini San Francisco', 0, 0, 'In Stock'),
('Licorice', 'Seattle', 0, 0, 'In Production'),
('Licorice', 'Seattle', 0, 0, 'Produced'),
('Licorice', 'Seattle', 0, 0, 'In Stock'),
('Licorice', 'Texas', 0, 0, 'In Production'),
('Licorice', 'Texas', 0, 0, 'Produced'),
('Licorice', 'Texas', 0, 0, 'In Stock'),
('Licorice', 'Vegas 80', 0, 0, 'In Production'),
('Licorice', 'Vegas 80', 0, 0, 'Produced'),
('Licorice', 'Vegas 80', 0, 0, 'In Stock'),
('Licorice', 'Vegas 60', 0, 0, 'In Production'),
('Licorice', 'Vegas 60', 0, 0, 'Produced'),
('Licorice', 'Vegas 60', 0, 0, 'In Stock'),
('Licorice', 'Venice', 0, 0, 'In Production'),
('Licorice', 'Venice', 0, 0, 'Produced'),
('Licorice', 'Venice', 0, 0, 'In Stock'),
('Licorice', 'Washington', 0, 0, 'In Production'),
('Licorice', 'Washington', 0, 0, 'Produced'),
('Licorice', 'Washington', 0, 0, 'In Stock'),
('Licorice', 'Inner Planter', 0, 0, 'In Production'),
('Licorice', 'Inner Planter', 0, 0, 'Produced'),
('Licorice', 'Inner Planter', 0, 0, 'In Stock'),
('Licorice', 'Outer Planter', 0, 0, 'In Production'),
('Licorice', 'Outer Planter', 0, 0, 'Produced'),
('Licorice', 'Outer Planter', 0, 0, 'In Stock'),
('Mustard', 'Atlanta', 0, 0, 'In Production'),
('Mustard', 'Atlanta', 0, 0, 'Produced'),
('Mustard', 'Atlanta', 0, 0, 'In Stock'),
('Mustard', 'Boston', 0, 0, 'In Production'),
('Mustard', 'Boston', 0, 0, 'Produced'),
('Mustard', 'Boston', 0, 0, 'In Stock'),
('Mustard', 'Carmel', 0, 0, 'In Production'),
('Mustard', 'Carmel', 0, 0, 'Produced'),
('Mustard', 'Carmel', 0, 0, 'In Stock'),
('Mustard', 'Charleston', 0, 0, 'In Production'),
('Mustard', 'Charleston', 0, 0, 'Produced'),
('Mustard', 'Charleston', 0, 0, 'In Stock'),
('Mustard', 'Chicago', 0, 0, 'In Production'),
('Mustard', 'Chicago', 0, 0, 'Produced'),
('Mustard', 'Chicago', 0, 0, 'In Stock'),
('Mustard', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Mustard', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Mustard', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Mustard', 'Denver', 0, 0, 'In Production'),
('Mustard', 'Denver', 0, 0, 'Produced'),
('Mustard', 'Denver', 0, 0, 'In Stock'),
('Mustard', 'HD Round', 0, 0, 'In Production'),
('Mustard', 'HD Round', 0, 0, 'Produced'),
('Mustard', 'HD Round', 0, 0, 'In Stock'),
('Mustard', 'Houston', 0, 0, 'In Production'),
('Mustard', 'Houston', 0, 0, 'Produced'),
('Mustard', 'Houston', 0, 0, 'In Stock'), 
('Mustard', 'Manhattan', 0, 0, 'In Production'),
('Mustard', 'Manhattan', 0, 0, 'Produced'),
('Mustard', 'Manhattan', 0, 0, 'In Stock'),
('Mustard', 'Mini Manhattan', 0, 0, 'In Production'),
('Mustard', 'Mini Manhattan', 0, 0, 'Produced'),
('Mustard', 'Mini Manhattan', 0, 0, 'In Stock'),
('Mustard', 'Miami', 0, 0, 'In Production'),
('Mustard', 'Miami', 0, 0, 'Produced'),
('Mustard', 'Miami', 0, 0, 'In Stock'),
('Mustard', 'Mini Miami', 0, 0, 'In Production'),
('Mustard', 'Mini Miami', 0, 0, 'Produced'),
('Mustard', 'Mini Miami', 0, 0, 'In Stock'),
('Mustard', 'Michu', 0, 0, 'In Production'),
('Mustard', 'Michu', 0, 0, 'Produced'),
('Mustard', 'Michu', 0, 0, 'In Stock'),
('Mustard', 'Michu Planter', 0, 0, 'In Production'),
('Mustard', 'Michu Planter', 0, 0, 'Produced'),
('Mustard', 'Michu Planter', 0, 0, 'In Stock'),
('Mustard', 'Minima', 0, 0, 'In Production'),
('Mustard', 'Minima', 0, 0, 'Produced'),
('Mustard', 'Minima', 0, 0, 'In Stock'),
('Mustard', 'New York', 0, 0, 'In Production'),
('Mustard', 'New York', 0, 0, 'Produced'),
('Mustard', 'New York', 0, 0, 'In Stock'),
('Mustard', 'New York 100', 0, 0, 'In Production'),
('Mustard', 'New York 100', 0, 0, 'Produced'),
('Mustard', 'New York 100', 0, 0, 'In Stock'),
('Mustard', 'Orlando', 0, 0, 'In Production'),
('Mustard', 'Orlando', 0, 0, 'Produced'),
('Mustard', 'Orlando', 0, 0, 'In Stock'),
('Mustard', 'Portland', 0, 0, 'In Production'),
('Mustard', 'Portland', 0, 0, 'Produced'),
('Mustard', 'Portland', 0, 0, 'In Stock'),
('Mustard', 'Phoenix', 0, 0, 'In Production'),
('Mustard', 'Phoenix', 0, 0, 'Produced'),
('Mustard', 'Phoenix', 0, 0, 'In Stock'),
('Mustard', 'Reno', 0, 0, 'In Production'),
('Mustard', 'Reno', 0, 0, 'Produced'),
('Mustard', 'Reno', 0, 0, 'In Stock'),
('Mustard', 'San Francisco New Mold', 0, 0, 'In Production'),
('Mustard', 'San Francisco New Mold', 0, 0, 'Produced'),
('Mustard', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Mustard', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Mustard', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Mustard', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Mustard', 'San Francisco ADA', 0, 0, 'In Production'),
('Mustard', 'San Francisco ADA', 0, 0, 'Produced'),
('Mustard', 'San Francisco ADA', 0, 0, 'In Stock'),
('Mustard', 'Mini San Francisco', 0, 0, 'In Production'),
('Mustard', 'Mini San Francisco', 0, 0, 'Produced'),
('Mustard', 'Mini San Francisco', 0, 0, 'In Stock'),
('Mustard', 'Seattle', 0, 0, 'In Production'),
('Mustard', 'Seattle', 0, 0, 'Produced'),
('Mustard', 'Seattle', 0, 0, 'In Stock'),
('Mustard', 'Texas', 0, 0, 'In Production'),
('Mustard', 'Texas', 0, 0, 'Produced'),
('Mustard', 'Texas', 0, 0, 'In Stock'),
('Mustard', 'Vegas 80', 0, 0, 'In Production'),
('Mustard', 'Vegas 80', 0, 0, 'Produced'),
('Mustard', 'Vegas 80', 0, 0, 'In Stock'),
('Mustard', 'Vegas 60', 0, 0, 'In Production'),
('Mustard', 'Vegas 60', 0, 0, 'Produced'),
('Mustard', 'Vegas 60', 0, 0, 'In Stock'),
('Mustard', 'Venice', 0, 0, 'In Production'),
('Mustard', 'Venice', 0, 0, 'Produced'),
('Mustard', 'Venice', 0, 0, 'In Stock'),
('Mustard', 'Washington', 0, 0, 'In Production'),
('Mustard', 'Washington', 0, 0, 'Produced'),
('Mustard', 'Washington', 0, 0, 'In Stock'),
('Mustard', 'Inner Planter', 0, 0, 'In Production'),
('Mustard', 'Inner Planter', 0, 0, 'Produced'),
('Mustard', 'Inner Planter', 0, 0, 'In Stock'),
('Mustard', 'Outer Planter', 0, 0, 'In Production'),
('Mustard', 'Outer Planter', 0, 0, 'Produced'),
('Mustard', 'Outer Planter', 0, 0, 'In Stock'),
('Nude', 'Atlanta', 0, 0, 'In Production'),
('Nude', 'Atlanta', 0, 0, 'Produced'),
('Nude', 'Atlanta', 0, 0, 'In Stock'),
('Nude', 'Boston', 0, 0, 'In Production'),
('Nude', 'Boston', 0, 0, 'Produced'),
('Nude', 'Boston', 0, 0, 'In Stock'),
('Nude', 'Carmel', 0, 0, 'In Production'),
('Nude', 'Carmel', 0, 0, 'Produced'),
('Nude', 'Carmel', 0, 0, 'In Stock'),
('Nude', 'Charleston', 0, 0, 'In Production'),
('Nude', 'Charleston', 0, 0, 'Produced'),
('Nude', 'Charleston', 0, 0, 'In Stock'),
('Nude', 'Chicago', 0, 0, 'In Production'),
('Nude', 'Chicago', 0, 0, 'Produced'),
('Nude', 'Chicago', 0, 0, 'In Stock'),
('Nude', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Nude', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Nude', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Nude', 'Denver', 0, 0, 'In Production'),
('Nude', 'Denver', 0, 0, 'Produced'),
('Nude', 'Denver', 0, 0, 'In Stock'),
('Nude', 'HD Round', 0, 0, 'In Production'),
('Nude', 'HD Round', 0, 0, 'Produced'),
('Nude', 'HD Round', 0, 0, 'In Stock'),
('Nude', 'Houston', 0, 0, 'In Production'),
('Nude', 'Houston', 0, 0, 'Produced'),
('Nude', 'Houston', 0, 0, 'In Stock'),
('Nude', 'Manhattan', 0, 0, 'In Production'),
('Nude', 'Manhattan', 0, 0, 'Produced'),
('Nude', 'Manhattan', 0, 0, 'In Stock'),
('Nude', 'Mini Manhattan', 0, 0, 'In Production'),
('Nude', 'Mini Manhattan', 0, 0, 'Produced'),
('Nude', 'Mini Manhattan', 0, 0, 'In Stock'),
('Nude', 'Miami', 0, 0, 'In Production'),
('Nude', 'Miami', 0, 0, 'Produced'),
('Nude', 'Miami', 0, 0, 'In Stock'),
('Nude', 'Mini Miami', 0, 0, 'In Production'),
('Nude', 'Mini Miami', 0, 0, 'Produced'),
('Nude', 'Mini Miami', 0, 0, 'In Stock'),
('Nude', 'Michu', 0, 0, 'In Production'),
('Nude', 'Michu', 0, 0, 'Produced'),
('Nude', 'Michu', 0, 0, 'In Stock'),
('Nude', 'Michu Planter', 0, 0, 'In Production'),
('Nude', 'Michu Planter', 0, 0, 'Produced'),
('Nude', 'Michu Planter', 0, 0, 'In Stock'),
('Nude', 'Minima', 0, 0, 'In Production'),
('Nude', 'Minima', 0, 0, 'Produced'),
('Nude', 'Minima', 0, 0, 'In Stock'),
('Nude', 'New York', 0, 0, 'In Production'),
('Nude', 'New York', 0, 0, 'Produced'),
('Nude', 'New York', 0, 0, 'In Stock'),
('Nude', 'New York 100', 0, 0, 'In Production'),
('Nude', 'New York 100', 0, 0, 'Produced'),
('Nude', 'New York 100', 0, 0, 'In Stock'),
('Nude', 'Orlando', 0, 0, 'In Production'),
('Nude', 'Orlando', 0, 0, 'Produced'),
('Nude', 'Orlando', 0, 0, 'In Stock'),
('Nude', 'Portland', 0, 0, 'In Production'),
('Nude', 'Portland', 0, 0, 'Produced'),
('Nude', 'Portland', 0, 0, 'In Stock'),
('Nude', 'Phoenix', 0, 0, 'In Production'),
('Nude', 'Phoenix', 0, 0, 'Produced'),
('Nude', 'Phoenix', 0, 0, 'In Stock'),
('Nude', 'Reno', 0, 0, 'In Production'),
('Nude', 'Reno', 0, 0, 'Produced'),
('Nude', 'Reno', 0, 0, 'In Stock'),
('Nude', 'San Francisco New Mold', 0, 0, 'In Production'),
('Nude', 'San Francisco New Mold', 0, 0, 'Produced'),
('Nude', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Nude', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Nude', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Nude', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Nude', 'San Francisco ADA', 0, 0, 'In Production'),
('Nude', 'San Francisco ADA', 0, 0, 'Produced'),
('Nude', 'San Francisco ADA', 0, 0, 'In Stock'),
('Nude', 'Mini San Francisco', 0, 0, 'In Production'),
('Nude', 'Mini San Francisco', 0, 0, 'Produced'),
('Nude', 'Mini San Francisco', 0, 0, 'In Stock'),
('Nude', 'Seattle', 0, 0, 'In Production'),
('Nude', 'Seattle', 0, 0, 'Produced'),
('Nude', 'Seattle', 0, 0, 'In Stock'),
('Nude', 'Texas', 0, 0, 'In Production'),
('Nude', 'Texas', 0, 0, 'Produced'),
('Nude', 'Texas', 0, 0, 'In Stock'),
('Nude', 'Vegas 80', 0, 0, 'In Production'),
('Nude', 'Vegas 80', 0, 0, 'Produced'),
('Nude', 'Vegas 80', 0, 0, 'In Stock'),
('Nude', 'Vegas 60', 0, 0, 'In Production'),
('Nude', 'Vegas 60', 0, 0, 'Produced'),
('Nude', 'Vegas 60', 0, 0, 'In Stock'),
('Nude', 'Venice', 0, 0, 'In Production'),
('Nude', 'Venice', 0, 0, 'Produced'),
('Nude', 'Venice', 0, 0, 'In Stock'),
('Nude', 'Washington', 0, 0, 'In Production'),
('Nude', 'Washington', 0, 0, 'Produced'),
('Nude', 'Washington', 0, 0, 'In Stock'),
('Nude', 'Inner Planter', 0, 0, 'In Production'),
('Nude', 'Inner Planter', 0, 0, 'Produced'),
('Nude', 'Inner Planter', 0, 0, 'In Stock'),
('Nude', 'Outer Planter', 0, 0, 'In Production'), 
('Nude', 'Outer Planter', 0, 0, 'Produced'),
('Nude', 'Outer Planter', 0, 0, 'In Stock'),
('Peach', 'Atlanta', 0, 0, 'In Production'),
('Peach', 'Atlanta', 0, 0, 'Produced'),
('Peach', 'Atlanta', 0, 0, 'In Stock'),
('Peach', 'Boston', 0, 0, 'In Production'),
('Peach', 'Boston', 0, 0, 'Produced'),
('Peach', 'Boston', 0, 0, 'In Stock'),
('Peach', 'Carmel', 0, 0, 'In Production'),
('Peach', 'Carmel', 0, 0, 'Produced'),
('Peach', 'Carmel', 0, 0, 'In Stock'),
('Peach', 'Charleston', 0, 0, 'In Production'),
('Peach', 'Charleston', 0, 0, 'Produced'),
('Peach', 'Charleston', 0, 0, 'In Stock'),
('Peach', 'Chicago', 0, 0, 'In Production'),
('Peach', 'Chicago', 0, 0, 'Produced'),
('Peach', 'Chicago', 0, 0, 'In Stock'),
('Peach', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Peach', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Peach', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Peach', 'Denver', 0, 0, 'In Production'),
('Peach', 'Denver', 0, 0, 'Produced'),
('Peach', 'Denver', 0, 0, 'In Stock'),
('Peach', 'HD Round', 0, 0, 'In Production'),
('Peach', 'HD Round', 0, 0, 'Produced'),
('Peach', 'HD Round', 0, 0, 'In Stock'),
('Peach', 'Houston', 0, 0, 'In Production'),
('Peach', 'Houston', 0, 0, 'Produced'),
('Peach', 'Houston', 0, 0, 'In Stock'),
('Peach', 'Manhattan', 0, 0, 'In Production'),
('Peach', 'Manhattan', 0, 0, 'Produced'),
('Peach', 'Manhattan', 0, 0, 'In Stock'),
('Peach', 'Mini Manhattan', 0, 0, 'In Production'),
('Peach', 'Mini Manhattan', 0, 0, 'Produced'),
('Peach', 'Mini Manhattan', 0, 0, 'In Stock'),
('Peach', 'Miami', 0, 0, 'In Production'),
('Peach', 'Miami', 0, 0, 'Produced'),
('Peach', 'Miami', 0, 0, 'In Stock'),
('Peach', 'Mini Miami', 0, 0, 'In Production'),
('Peach', 'Mini Miami', 0, 0, 'Produced'),
('Peach', 'Mini Miami', 0, 0, 'In Stock'),
('Peach', 'Michu', 0, 0, 'In Production'),
('Peach', 'Michu', 0, 0, 'Produced'),
('Peach', 'Michu', 0, 0, 'In Stock'),
('Peach', 'Michu Planter', 0, 0, 'In Production'),
('Peach', 'Michu Planter', 0, 0, 'Produced'),
('Peach', 'Michu Planter', 0, 0, 'In Stock'),
('Peach', 'Minima', 0, 0, 'In Production'),
('Peach', 'Minima', 0, 0, 'Produced'),
('Peach', 'Minima', 0, 0, 'In Stock'),
('Peach', 'New York', 0, 0, 'In Production'),
('Peach', 'New York', 0, 0, 'Produced'),
('Peach', 'New York', 0, 0, 'In Stock'),
('Peach', 'New York 100', 0, 0, 'In Production'),
('Peach', 'New York 100', 0, 0, 'Produced'),
('Peach', 'New York 100', 0, 0, 'In Stock'),
('Peach', 'Orlando', 0, 0, 'In Production'),
('Peach', 'Orlando', 0, 0, 'Produced'),
('Peach', 'Orlando', 0, 0, 'In Stock'),
('Peach', 'Portland', 0, 0, 'In Production'),
('Peach', 'Portland', 0, 0, 'Produced'),
('Peach', 'Portland', 0, 0, 'In Stock'),
('Peach', 'Phoenix', 0, 0, 'In Production'),
('Peach', 'Phoenix', 0, 0, 'Produced'),
('Peach', 'Phoenix', 0, 0, 'In Stock'),
('Peach', 'Reno', 0, 0, 'In Production'),
('Peach', 'Reno', 0, 0, 'Produced'),
('Peach', 'Reno', 0, 0, 'In Stock'),
('Peach', 'San Francisco New Mold', 0, 0, 'In Production'),
('Peach', 'San Francisco New Mold', 0, 0, 'Produced'),
('Peach', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Peach', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Peach', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Peach', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Peach', 'San Francisco ADA', 0, 0, 'In Production'),
('Peach', 'San Francisco ADA', 0, 0, 'Produced'),
('Peach', 'San Francisco ADA', 0, 0, 'In Stock'),
('Peach', 'Mini San Francisco', 0, 0, 'In Production'),
('Peach', 'Mini San Francisco', 0, 0, 'Produced'),
('Peach', 'Mini San Francisco', 0, 0, 'In Stock'),
('Peach', 'Seattle', 0, 0, 'In Production'),
('Peach', 'Seattle', 0, 0, 'Produced'),
('Peach', 'Seattle', 0, 0, 'In Stock'),
('Peach', 'Texas', 0, 0, 'In Production'),
('Peach', 'Texas', 0, 0, 'Produced'),
('Peach', 'Texas', 0, 0, 'In Stock'),
('Peach', 'Vegas 80', 0, 0, 'In Production'),
('Peach', 'Vegas 80', 0, 0, 'Produced'),
('Peach', 'Vegas 80', 0, 0, 'In Stock'),
('Peach', 'Vegas 60', 0, 0, 'In Production'),
('Peach', 'Vegas 60', 0, 0, 'Produced'),
('Peach', 'Vegas 60', 0, 0, 'In Stock'),
('Peach', 'Venice', 0, 0, 'In Production'),
('Peach', 'Venice', 0, 0, 'Produced'),
('Peach', 'Venice', 0, 0, 'In Stock'),
('Peach', 'Washington', 0, 0, 'In Production'),
('Peach', 'Washington', 0, 0, 'Produced'),
('Peach', 'Washington', 0, 0, 'In Stock'),
('Peach', 'Inner Planter', 0, 0, 'In Production'),
('Peach', 'Inner Planter', 0, 0, 'Produced'),
('Peach', 'Inner Planter', 0, 0, 'In Stock'),
('Peach', 'Outer Planter', 0, 0, 'In Production'),
('Peach', 'Outer Planter', 0, 0, 'Produced'),
('Peach', 'Outer Planter', 0, 0, 'In Stock'),
('Pistachio', 'Atlanta', 0, 0, 'In Production'),
('Pistachio', 'Atlanta', 0, 0, 'Produced'),
('Pistachio', 'Atlanta', 0, 0, 'In Stock'),
('Pistachio', 'Boston', 0, 0, 'In Production'),
('Pistachio', 'Boston', 0, 0, 'Produced'),
('Pistachio', 'Boston', 0, 0, 'In Stock'),
('Pistachio', 'Carmel', 0, 0, 'In Production'),
('Pistachio', 'Carmel', 0, 0, 'Produced'),
('Pistachio', 'Carmel', 0, 0, 'In Stock'),
('Pistachio', 'Charleston', 0, 0, 'In Production'),
('Pistachio', 'Charleston', 0, 0, 'Produced'),
('Pistachio', 'Charleston', 0, 0, 'In Stock'),
('Pistachio', 'Chicago', 0, 0, 'In Production'),
('Pistachio', 'Chicago', 0, 0, 'Produced'),
('Pistachio', 'Chicago', 0, 0, 'In Stock'),
('Pistachio', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Pistachio', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Pistachio', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Pistachio', 'Denver', 0, 0, 'In Production'),
('Pistachio', 'Denver', 0, 0, 'Produced'),
('Pistachio', 'Denver', 0, 0, 'In Stock'),
('Pistachio', 'HD Round', 0, 0, 'In Production'),
('Pistachio', 'HD Round', 0, 0, 'Produced'),
('Pistachio', 'HD Round', 0, 0, 'In Stock'),
('Pistachio', 'Houston', 0, 0, 'In Production'),
('Pistachio', 'Houston', 0, 0, 'Produced'),
('Pistachio', 'Houston', 0, 0, 'In Stock'),
('Pistachio', 'Manhattan', 0, 0, 'In Production'),
('Pistachio', 'Manhattan', 0, 0, 'Produced'),
('Pistachio', 'Manhattan', 0, 0, 'In Stock'),
('Pistachio', 'Mini Manhattan', 0, 0, 'In Production'),
('Pistachio', 'Mini Manhattan', 0, 0, 'Produced'),
('Pistachio', 'Mini Manhattan', 0, 0, 'In Stock'),
('Pistachio', 'Miami', 0, 0, 'In Production'),
('Pistachio', 'Miami', 0, 0, 'Produced'),
('Pistachio', 'Miami', 0, 0, 'In Stock'),
('Pistachio', 'Mini Miami', 0, 0, 'In Production'),
('Pistachio', 'Mini Miami', 0, 0, 'Produced'),
('Pistachio', 'Mini Miami', 0, 0, 'In Stock'),
('Pistachio', 'Michu', 0, 0, 'In Production'),
('Pistachio', 'Michu', 0, 0, 'Produced'),
('Pistachio', 'Michu', 0, 0, 'In Stock'),
('Pistachio', 'Michu Planter', 0, 0, 'In Production'),
('Pistachio', 'Michu Planter', 0, 0, 'Produced'),
('Pistachio', 'Michu Planter', 0, 0, 'In Stock'),
('Pistachio', 'Minima', 0, 0, 'In Production'),
('Pistachio', 'Minima', 0, 0, 'Produced'),
('Pistachio', 'Minima', 0, 0, 'In Stock'),
('Pistachio', 'New York', 0, 0, 'In Production'),
('Pistachio', 'New York', 0, 0, 'Produced'),
('Pistachio', 'New York', 0, 0, 'In Stock'),
('Pistachio', 'New York 100', 0, 0, 'In Production'),
('Pistachio', 'New York 100', 0, 0, 'Produced'),
('Pistachio', 'New York 100', 0, 0, 'In Stock'),
('Pistachio', 'Orlando', 0, 0, 'In Production'),
('Pistachio', 'Orlando', 0, 0, 'Produced'),
('Pistachio', 'Orlando', 0, 0, 'In Stock'),
('Pistachio', 'Portland', 0, 0, 'In Production'),
('Pistachio', 'Portland', 0, 0, 'Produced'),
('Pistachio', 'Portland', 0, 0, 'In Stock'),
('Pistachio', 'Phoenix', 0, 0, 'In Production'),
('Pistachio', 'Phoenix', 0, 0, 'Produced'),
('Pistachio', 'Phoenix', 0, 0, 'In Stock'),
('Pistachio', 'Reno', 0, 0, 'In Production'),
('Pistachio', 'Reno', 0, 0, 'Produced'),
('Pistachio', 'Reno', 0, 0, 'In Stock'),
('Pistachio', 'San Francisco New Mold', 0, 0, 'In Production'),
('Pistachio', 'San Francisco New Mold', 0, 0, 'Produced'), 
('Pistachio', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Pistachio', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Pistachio', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Pistachio', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Pistachio', 'San Francisco ADA', 0, 0, 'In Production'),
('Pistachio', 'San Francisco ADA', 0, 0, 'Produced'),
('Pistachio', 'San Francisco ADA', 0, 0, 'In Stock'),
('Pistachio', 'Mini San Francisco', 0, 0, 'In Production'),
('Pistachio', 'Mini San Francisco', 0, 0, 'Produced'),
('Pistachio', 'Mini San Francisco', 0, 0, 'In Stock'),
('Pistachio', 'Seattle', 0, 0, 'In Production'),
('Pistachio', 'Seattle', 0, 0, 'Produced'),
('Pistachio', 'Seattle', 0, 0, 'In Stock'),
('Pistachio', 'Texas', 0, 0, 'In Production'),
('Pistachio', 'Texas', 0, 0, 'Produced'),
('Pistachio', 'Texas', 0, 0, 'In Stock'),
('Pistachio', 'Vegas 80', 0, 0, 'In Production'),
('Pistachio', 'Vegas 80', 0, 0, 'Produced'),
('Pistachio', 'Vegas 80', 0, 0, 'In Stock'),
('Pistachio', 'Vegas 60', 0, 0, 'In Production'),
('Pistachio', 'Vegas 60', 0, 0, 'Produced'),
('Pistachio', 'Vegas 60', 0, 0, 'In Stock'),
('Pistachio', 'Venice', 0, 0, 'In Production'),
('Pistachio', 'Venice', 0, 0, 'Produced'),
('Pistachio', 'Venice', 0, 0, 'In Stock'),
('Pistachio', 'Washington', 0, 0, 'In Production'),
('Pistachio', 'Washington', 0, 0, 'Produced'),
('Pistachio', 'Washington', 0, 0, 'In Stock'),
('Pistachio', 'Inner Planter', 0, 0, 'In Production'),
('Pistachio', 'Inner Planter', 0, 0, 'Produced'),
('Pistachio', 'Inner Planter', 0, 0, 'In Stock'),
('Pistachio', 'Outer Planter', 0, 0, 'In Production'),
('Pistachio', 'Outer Planter', 0, 0, 'Produced'),
('Pistachio', 'Outer Planter', 0, 0, 'In Stock'),
('Platinum', 'Atlanta', 0, 0, 'In Production'),
('Platinum', 'Atlanta', 0, 0, 'Produced'),
('Platinum', 'Atlanta', 0, 0, 'In Stock'),
('Platinum', 'Boston', 0, 0, 'In Production'),
('Platinum', 'Boston', 0, 0, 'Produced'),
('Platinum', 'Boston', 0, 0, 'In Stock'),
('Platinum', 'Carmel', 0, 0, 'In Production'),
('Platinum', 'Carmel', 0, 0, 'Produced'),
('Platinum', 'Carmel', 0, 0, 'In Stock'),
('Platinum', 'Charleston', 0, 0, 'In Production'),
('Platinum', 'Charleston', 0, 0, 'Produced'),
('Platinum', 'Charleston', 0, 0, 'In Stock'),
('Platinum', 'Chicago', 0, 0, 'In Production'),
('Platinum', 'Chicago', 0, 0, 'Produced'),
('Platinum', 'Chicago', 0, 0, 'In Stock'),
('Platinum', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Platinum', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Platinum', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Platinum', 'Denver', 0, 0, 'In Production'),
('Platinum', 'Denver', 0, 0, 'Produced'),
('Platinum', 'Denver', 0, 0, 'In Stock'),
('Platinum', 'HD Round', 0, 0, 'In Production'),
('Platinum', 'HD Round', 0, 0, 'Produced'),
('Platinum', 'HD Round', 0, 0, 'In Stock'),
('Platinum', 'Houston', 0, 0, 'In Production'),
('Platinum', 'Houston', 0, 0, 'Produced'),
('Platinum', 'Houston', 0, 0, 'In Stock'),
('Platinum', 'Manhattan', 0, 0, 'In Production'),
('Platinum', 'Manhattan', 0, 0, 'Produced'),
('Platinum', 'Manhattan', 0, 0, 'In Stock'),
('Platinum', 'Mini Manhattan', 0, 0, 'In Production'),
('Platinum', 'Mini Manhattan', 0, 0, 'Produced'),
('Platinum', 'Mini Manhattan', 0, 0, 'In Stock'),
('Platinum', 'Miami', 0, 0, 'In Production'),
('Platinum', 'Miami', 0, 0, 'Produced'),
('Platinum', 'Miami', 0, 0, 'In Stock'),
('Platinum', 'Mini Miami', 0, 0, 'In Production'),
('Platinum', 'Mini Miami', 0, 0, 'Produced'),
('Platinum', 'Mini Miami', 0, 0, 'In Stock'),
('Platinum', 'Michu', 0, 0, 'In Production'),
('Platinum', 'Michu', 0, 0, 'Produced'),
('Platinum', 'Michu', 0, 0, 'In Stock'),
('Platinum', 'Michu Planter', 0, 0, 'In Production'),
('Platinum', 'Michu Planter', 0, 0, 'Produced'),
('Platinum', 'Michu Planter', 0, 0, 'In Stock'),
('Platinum', 'Minima', 0, 0, 'In Production'),
('Platinum', 'Minima', 0, 0, 'Produced'),
('Platinum', 'Minima', 0, 0, 'In Stock'),
('Platinum', 'New York', 0, 0, 'In Production'),
('Platinum', 'New York', 0, 0, 'Produced'),
('Platinum', 'New York', 0, 0, 'In Stock'),
('Platinum', 'New York 100', 0, 0, 'In Production'),
('Platinum', 'New York 100', 0, 0, 'Produced'),
('Platinum', 'New York 100', 0, 0, 'In Stock'),
('Platinum', 'Orlando', 0, 0, 'In Production'),
('Platinum', 'Orlando', 0, 0, 'Produced'),
('Platinum', 'Orlando', 0, 0, 'In Stock'),
('Platinum', 'Portland', 0, 0, 'In Production'),
('Platinum', 'Portland', 0, 0, 'Produced'),
('Platinum', 'Portland', 0, 0, 'In Stock'),
('Platinum', 'Phoenix', 0, 0, 'In Production'),
('Platinum', 'Phoenix', 0, 0, 'Produced'),
('Platinum', 'Phoenix', 0, 0, 'In Stock'),
('Platinum', 'Reno', 0, 0, 'In Production'),
('Platinum', 'Reno', 0, 0, 'Produced'),
('Platinum', 'Reno', 0, 0, 'In Stock'),
('Platinum', 'San Francisco New Mold', 0, 0, 'In Production'),
('Platinum', 'San Francisco New Mold', 0, 0, 'Produced'),
('Platinum', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Platinum', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Platinum', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Platinum', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Platinum', 'San Francisco ADA', 0, 0, 'In Production'),
('Platinum', 'San Francisco ADA', 0, 0, 'Produced'),
('Platinum', 'San Francisco ADA', 0, 0, 'In Stock'),
('Platinum', 'Mini San Francisco', 0, 0, 'In Production'),
('Platinum', 'Mini San Francisco', 0, 0, 'Produced'),
('Platinum', 'Mini San Francisco', 0, 0, 'In Stock'),
('Platinum', 'Seattle', 0, 0, 'In Production'),
('Platinum', 'Seattle', 0, 0, 'Produced'),
('Platinum', 'Seattle', 0, 0, 'In Stock'),
('Platinum', 'Texas', 0, 0, 'In Production'),
('Platinum', 'Texas', 0, 0, 'Produced'),
('Platinum', 'Texas', 0, 0, 'In Stock'),
('Platinum', 'Vegas 80', 0, 0, 'In Production'),
('Platinum', 'Vegas 80', 0, 0, 'Produced'),
('Platinum', 'Vegas 80', 0, 0, 'In Stock'),
('Platinum', 'Vegas 60', 0, 0, 'In Production'),
('Platinum', 'Vegas 60', 0, 0, 'Produced'),
('Platinum', 'Vegas 60', 0, 0, 'In Stock'),
('Platinum', 'Venice', 0, 0, 'In Production'),
('Platinum', 'Venice', 0, 0, 'Produced'),
('Platinum', 'Venice', 0, 0, 'In Stock'),
('Platinum', 'Washington', 0, 0, 'In Production'),
('Platinum', 'Washington', 0, 0, 'Produced'),
('Platinum', 'Washington', 0, 0, 'In Stock'),
('Platinum', 'Inner Planter', 0, 0, 'In Production'),
('Platinum', 'Inner Planter', 0, 0, 'Produced'),
('Platinum', 'Inner Planter', 0, 0, 'In Stock'),
('Platinum', 'Outer Planter', 0, 0, 'In Production'),
('Platinum', 'Outer Planter', 0, 0, 'Produced'),
('Platinum', 'Outer Planter', 0, 0, 'In Stock'),
('Red', 'Atlanta', 0, 0, 'In Production'),
('Red', 'Atlanta', 0, 0, 'Produced'),
('Red', 'Atlanta', 0, 0, 'In Stock'),
('Red', 'Boston', 0, 0, 'In Production'),
('Red', 'Boston', 0, 0, 'Produced'),
('Red', 'Boston', 0, 0, 'In Stock'),
('Red', 'Carmel', 0, 0, 'In Production'),
('Red', 'Carmel', 0, 0, 'Produced'),
('Red', 'Carmel', 0, 0, 'In Stock'),
('Red', 'Charleston', 0, 0, 'In Production'),
('Red', 'Charleston', 0, 0, 'Produced'),
('Red', 'Charleston', 0, 0, 'In Stock'),
('Red', 'Chicago', 0, 0, 'In Production'),
('Red', 'Chicago', 0, 0, 'Produced'),
('Red', 'Chicago', 0, 0, 'In Stock'),
('Red', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Red', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Red', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Red', 'Denver', 0, 0, 'In Production'),
('Red', 'Denver', 0, 0, 'Produced'),
('Red', 'Denver', 0, 0, 'In Stock'),
('Red', 'HD Round', 0, 0, 'In Production'),
('Red', 'HD Round', 0, 0, 'Produced'),
('Red', 'HD Round', 0, 0, 'In Stock'),
('Red', 'Houston', 0, 0, 'In Production'),
('Red', 'Houston', 0, 0, 'Produced'),
('Red', 'Houston', 0, 0, 'In Stock'),
('Red', 'Manhattan', 0, 0, 'In Production'),
('Red', 'Manhattan', 0, 0, 'Produced'),
('Red', 'Manhattan', 0, 0, 'In Stock'),
('Red', 'Mini Manhattan', 0, 0, 'In Production'),
('Red', 'Mini Manhattan', 0, 0, 'Produced'),
('Red', 'Mini Manhattan', 0, 0, 'In Stock'),
('Red', 'Miami', 0, 0, 'In Production'),
('Red', 'Miami', 0, 0, 'Produced'),
('Red', 'Miami', 0, 0, 'In Stock'),
('Red', 'Mini Miami', 0, 0, 'In Production'),
('Red', 'Mini Miami', 0, 0, 'Produced'),
('Red', 'Mini Miami', 0, 0, 'In Stock'),
('Red', 'Michu', 0, 0, 'In Production'),
('Red', 'Michu', 0, 0, 'Produced'),
('Red', 'Michu', 0, 0, 'In Stock'),
('Red', 'Michu Planter', 0, 0, 'In Production'),
('Red', 'Michu Planter', 0, 0, 'Produced'),
('Red', 'Michu Planter', 0, 0, 'In Stock'),
('Red', 'Minima', 0, 0, 'In Production'),
('Red', 'Minima', 0, 0, 'Produced'),
('Red', 'Minima', 0, 0, 'In Stock'),
('Red', 'New York', 0, 0, 'In Production'),
('Red', 'New York', 0, 0, 'Produced'),
('Red', 'New York', 0, 0, 'In Stock'),
('Red', 'New York 100', 0, 0, 'In Production'),
('Red', 'New York 100', 0, 0, 'Produced'),
('Red', 'New York 100', 0, 0, 'In Stock'),
('Red', 'Orlando', 0, 0, 'In Production'),
('Red', 'Orlando', 0, 0, 'Produced'),
('Red', 'Orlando', 0, 0, 'In Stock'),
('Red', 'Portland', 0, 0, 'In Production'),
('Red', 'Portland', 0, 0, 'Produced'),
('Red', 'Portland', 0, 0, 'In Stock'),
('Red', 'Phoenix', 0, 0, 'In Production'),
('Red', 'Phoenix', 0, 0, 'Produced'),
('Red', 'Phoenix', 0, 0, 'In Stock'),
('Red', 'Reno', 0, 0, 'In Production'),
('Red', 'Reno', 0, 0, 'Produced'),
('Red', 'Reno', 0, 0, 'In Stock'),
('Red', 'San Francisco New Mold', 0, 0, 'In Production'),
('Red', 'San Francisco New Mold', 0, 0, 'Produced'),
('Red', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Red', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Red', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Red', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Red', 'San Francisco ADA', 0, 0, 'In Production'),
('Red', 'San Francisco ADA', 0, 0, 'Produced'),
('Red', 'San Francisco ADA', 0, 0, 'In Stock'),
('Red', 'Mini San Francisco', 0, 0, 'In Production'),
('Red', 'Mini San Francisco', 0, 0, 'Produced'),
('Red', 'Mini San Francisco', 0, 0, 'In Stock'),
('Red', 'Seattle', 0, 0, 'In Production'),
('Red', 'Seattle', 0, 0, 'Produced'),
('Red', 'Seattle', 0, 0, 'In Stock'),
('Red', 'Texas', 0, 0, 'In Production'),
('Red', 'Texas', 0, 0, 'Produced'),
('Red', 'Texas', 0, 0, 'In Stock'),
('Red', 'Vegas 80', 0, 0, 'In Production'),
('Red', 'Vegas 80', 0, 0, 'Produced'),
('Red', 'Vegas 80', 0, 0, 'In Stock'),
('Red', 'Vegas 60', 0, 0, 'In Production'),
('Red', 'Vegas 60', 0, 0, 'Produced'),
('Red', 'Vegas 60', 0, 0, 'In Stock'),
('Red', 'Venice', 0, 0, 'In Production'),
('Red', 'Venice', 0, 0, 'Produced'),
('Red', 'Venice', 0, 0, 'In Stock'),
('Red', 'Washington', 0, 0, 'In Production'),
('Red', 'Washington', 0, 0, 'Produced'),
('Red', 'Washington', 0, 0, 'In Stock'),
('Red', 'Inner Planter', 0, 0, 'In Production'),
('Red', 'Inner Planter', 0, 0, 'Produced'),
('Red', 'Inner Planter', 0, 0, 'In Stock'),
('Red', 'Outer Planter', 0, 0, 'In Production'),
('Red', 'Outer Planter', 0, 0, 'Produced'),
('Red', 'Outer Planter', 0, 0, 'In Stock'),
('Stone', 'Atlanta', 0, 0, 'In Production'),
('Stone', 'Atlanta', 0, 0, 'Produced'),
('Stone', 'Atlanta', 0, 0, 'In Stock'),
('Stone', 'Boston', 0, 0, 'In Production'),
('Stone', 'Boston', 0, 0, 'Produced'),
('Stone', 'Boston', 0, 0, 'In Stock'),
('Stone', 'Carmel', 0, 0, 'In Production'),
('Stone', 'Carmel', 0, 0, 'Produced'),
('Stone', 'Carmel', 0, 0, 'In Stock'),
('Stone', 'Charleston', 0, 0, 'In Production'),
('Stone', 'Charleston', 0, 0, 'Produced'),
('Stone', 'Charleston', 0, 0, 'In Stock'),
('Stone', 'Chicago', 0, 0, 'In Production'),
('Stone', 'Chicago', 0, 0, 'Produced'),
('Stone', 'Chicago', 0, 0, 'In Stock'),
('Stone', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Stone', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Stone', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Stone', 'Denver', 0, 0, 'In Production'),
('Stone', 'Denver', 0, 0, 'Produced'),
('Stone', 'Denver', 0, 0, 'In Stock'),
('Stone', 'HD Round', 0, 0, 'In Production'),
('Stone', 'HD Round', 0, 0, 'Produced'),
('Stone', 'HD Round', 0, 0, 'In Stock'),
('Stone', 'Houston', 0, 0, 'In Production'),
('Stone', 'Houston', 0, 0, 'Produced'),
('Stone', 'Houston', 0, 0, 'In Stock'),
('Stone', 'Manhattan', 0, 0, 'In Production'),
('Stone', 'Manhattan', 0, 0, 'Produced'),
('Stone', 'Manhattan', 0, 0, 'In Stock'),
('Stone', 'Mini Manhattan', 0, 0, 'In Production'),
('Stone', 'Mini Manhattan', 0, 0, 'Produced'),
('Stone', 'Mini Manhattan', 0, 0, 'In Stock'),
('Stone', 'Miami', 0, 0, 'In Production'),
('Stone', 'Miami', 0, 0, 'Produced'),
('Stone', 'Miami', 0, 0, 'In Stock'),
('Stone', 'Mini Miami', 0, 0, 'In Production'),
('Stone', 'Mini Miami', 0, 0, 'Produced'),
('Stone', 'Mini Miami', 0, 0, 'In Stock'),
('Stone', 'Michu', 0, 0, 'In Production'),
('Stone', 'Michu', 0, 0, 'Produced'),
('Stone', 'Michu', 0, 0, 'In Stock'),
('Stone', 'Michu Planter', 0, 0, 'In Production'),
('Stone', 'Michu Planter', 0, 0, 'Produced'),
('Stone', 'Michu Planter', 0, 0, 'In Stock'),
('Stone', 'Minima', 0, 0, 'In Production'),
('Stone', 'Minima', 0, 0, 'Produced'),
('Stone', 'Minima', 0, 0, 'In Stock'),
('Stone', 'New York', 0, 0, 'In Production'),
('Stone', 'New York', 0, 0, 'Produced'),
('Stone', 'New York', 0, 0, 'In Stock'),
('Stone', 'New York 100', 0, 0, 'In Production'),
('Stone', 'New York 100', 0, 0, 'Produced'),
('Stone', 'New York 100', 0, 0, 'In Stock'),
('Stone', 'Orlando', 0, 0, 'In Production'),
('Stone', 'Orlando', 0, 0, 'Produced'),
('Stone', 'Orlando', 0, 0, 'In Stock'),
('Stone', 'Portland', 0, 0, 'In Production'),
('Stone', 'Portland', 0, 0, 'Produced'),
('Stone', 'Portland', 0, 0, 'In Stock'),
('Stone', 'Phoenix', 0, 0, 'In Production'),
('Stone', 'Phoenix', 0, 0, 'Produced'),
('Stone', 'Phoenix', 0, 0, 'In Stock'),
('Stone', 'Reno', 0, 0, 'In Production'),
('Stone', 'Reno', 0, 0, 'Produced'),
('Stone', 'Reno', 0, 0, 'In Stock'),
('Stone', 'San Francisco New Mold', 0, 0, 'In Production'),
('Stone', 'San Francisco New Mold', 0, 0, 'Produced'),
('Stone', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Stone', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Stone', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Stone', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Stone', 'San Francisco ADA', 0, 0, 'In Production'),
('Stone', 'San Francisco ADA', 0, 0, 'Produced'),
('Stone', 'San Francisco ADA', 0, 0, 'In Stock'),
('Stone', 'Mini San Francisco', 0, 0, 'In Production'),
('Stone', 'Mini San Francisco', 0, 0, 'Produced'),
('Stone', 'Mini San Francisco', 0, 0, 'In Stock'),
('Stone', 'Seattle', 0, 0, 'In Production'),
('Stone', 'Seattle', 0, 0, 'Produced'),
('Stone', 'Seattle', 0, 0, 'In Stock'),
('Stone', 'Texas', 0, 0, 'In Production'),
('Stone', 'Texas', 0, 0, 'Produced'),
('Stone', 'Texas', 0, 0, 'In Stock'),
('Stone', 'Vegas 80', 0, 0, 'In Production'),
('Stone', 'Vegas 80', 0, 0, 'Produced'),
('Stone', 'Vegas 80', 0, 0, 'In Stock'),
('Stone', 'Vegas 60', 0, 0, 'In Production'),
('Stone', 'Vegas 60', 0, 0, 'Produced'),
('Stone', 'Vegas 60', 0, 0, 'In Stock'),
('Stone', 'Venice', 0, 0, 'In Production'),
('Stone', 'Venice', 0, 0, 'Produced'),
('Stone', 'Venice', 0, 0, 'In Stock'),
('Stone', 'Washington', 0, 0, 'In Production'),
('Stone', 'Washington', 0, 0, 'Produced'),
('Stone', 'Washington', 0, 0, 'In Stock'),
('Stone', 'Inner Planter', 0, 0, 'In Production'),
('Stone', 'Inner Planter', 0, 0, 'Produced'),
('Stone', 'Inner Planter', 0, 0, 'In Stock'),
('Stone', 'Outer Planter', 0, 0, 'In Production'),
('Stone', 'Outer Planter', 0, 0, 'Produced'),
('Stone', 'Outer Planter', 0, 0, 'In Stock'),
('Tangerine', 'Atlanta', 0, 0, 'In Production'),
('Tangerine', 'Atlanta', 0, 0, 'Produced'),
('Tangerine', 'Atlanta', 0, 0, 'In Stock'),
('Tangerine', 'Boston', 0, 0, 'In Production'),
('Tangerine', 'Boston', 0, 0, 'Produced'), 
('Tangerine', 'Boston', 0, 0, 'In Stock'),
('Tangerine', 'Carmel', 0, 0, 'In Production'),
('Tangerine', 'Carmel', 0, 0, 'Produced'),
('Tangerine', 'Carmel', 0, 0, 'In Stock'),
('Tangerine', 'Charleston', 0, 0, 'In Production'),
('Tangerine', 'Charleston', 0, 0, 'Produced'),
('Tangerine', 'Charleston', 0, 0, 'In Stock'),
('Tangerine', 'Chicago', 0, 0, 'In Production'),
('Tangerine', 'Chicago', 0, 0, 'Produced'),
('Tangerine', 'Chicago', 0, 0, 'In Stock'),
('Tangerine', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Tangerine', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Tangerine', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Tangerine', 'Denver', 0, 0, 'In Production'),
('Tangerine', 'Denver', 0, 0, 'Produced'),
('Tangerine', 'Denver', 0, 0, 'In Stock'),
('Tangerine', 'HD Round', 0, 0, 'In Production'),
('Tangerine', 'HD Round', 0, 0, 'Produced'),
('Tangerine', 'HD Round', 0, 0, 'In Stock'),
('Tangerine', 'Houston', 0, 0, 'In Production'),
('Tangerine', 'Houston', 0, 0, 'Produced'),
('Tangerine', 'Houston', 0, 0, 'In Stock'),
('Tangerine', 'Manhattan', 0, 0, 'In Production'),
('Tangerine', 'Manhattan', 0, 0, 'Produced'),
('Tangerine', 'Manhattan', 0, 0, 'In Stock'),
('Tangerine', 'Mini Manhattan', 0, 0, 'In Production'),
('Tangerine', 'Mini Manhattan', 0, 0, 'Produced'),
('Tangerine', 'Mini Manhattan', 0, 0, 'In Stock'),
('Tangerine', 'Miami', 0, 0, 'In Production'),
('Tangerine', 'Miami', 0, 0, 'Produced'),
('Tangerine', 'Miami', 0, 0, 'In Stock'),
('Tangerine', 'Mini Miami', 0, 0, 'In Production'),
('Tangerine', 'Mini Miami', 0, 0, 'Produced'),
('Tangerine', 'Mini Miami', 0, 0, 'In Stock'),
('Tangerine', 'Michu', 0, 0, 'In Production'),
('Tangerine', 'Michu', 0, 0, 'Produced'),
('Tangerine', 'Michu', 0, 0, 'In Stock'),
('Tangerine', 'Michu Planter', 0, 0, 'In Production'),
('Tangerine', 'Michu Planter', 0, 0, 'Produced'),
('Tangerine', 'Michu Planter', 0, 0, 'In Stock'),
('Tangerine', 'Minima', 0, 0, 'In Production'),
('Tangerine', 'Minima', 0, 0, 'Produced'),
('Tangerine', 'Minima', 0, 0, 'In Stock'),
('Tangerine', 'New York', 0, 0, 'In Production'),
('Tangerine', 'New York', 0, 0, 'Produced'),
('Tangerine', 'New York', 0, 0, 'In Stock'),
('Tangerine', 'New York 100', 0, 0, 'In Production'),
('Tangerine', 'New York 100', 0, 0, 'Produced'),
('Tangerine', 'New York 100', 0, 0, 'In Stock'),
('Tangerine', 'Orlando', 0, 0, 'In Production'),
('Tangerine', 'Orlando', 0, 0, 'Produced'),
('Tangerine', 'Orlando', 0, 0, 'In Stock'),
('Tangerine', 'Portland', 0, 0, 'In Production'),
('Tangerine', 'Portland', 0, 0, 'Produced'),
('Tangerine', 'Portland', 0, 0, 'In Stock'),
('Tangerine', 'Phoenix', 0, 0, 'In Production'),
('Tangerine', 'Phoenix', 0, 0, 'Produced'),
('Tangerine', 'Phoenix', 0, 0, 'In Stock'),
('Tangerine', 'Reno', 0, 0, 'In Production'),
('Tangerine', 'Reno', 0, 0, 'Produced'),
('Tangerine', 'Reno', 0, 0, 'In Stock'),
('Tangerine', 'San Francisco New Mold', 0, 0, 'In Production'),
('Tangerine', 'San Francisco New Mold', 0, 0, 'Produced'),
('Tangerine', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Tangerine', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Tangerine', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Tangerine', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Tangerine', 'San Francisco ADA', 0, 0, 'In Production'),
('Tangerine', 'San Francisco ADA', 0, 0, 'Produced'),
('Tangerine', 'San Francisco ADA', 0, 0, 'In Stock'),
('Tangerine', 'Mini San Francisco', 0, 0, 'In Production'),
('Tangerine', 'Mini San Francisco', 0, 0, 'Produced'),
('Tangerine', 'Mini San Francisco', 0, 0, 'In Stock'),
('Tangerine', 'Seattle', 0, 0, 'In Production'),
('Tangerine', 'Seattle', 0, 0, 'Produced'),
('Tangerine', 'Seattle', 0, 0, 'In Stock'),
('Tangerine', 'Texas', 0, 0, 'In Production'),
('Tangerine', 'Texas', 0, 0, 'Produced'),
('Tangerine', 'Texas', 0, 0, 'In Stock'),
('Tangerine', 'Vegas 80', 0, 0, 'In Production'),
('Tangerine', 'Vegas 80', 0, 0, 'Produced'),
('Tangerine', 'Vegas 80', 0, 0, 'In Stock'),
('Tangerine', 'Vegas 60', 0, 0, 'In Production'),
('Tangerine', 'Vegas 60', 0, 0, 'Produced'),
('Tangerine', 'Vegas 60', 0, 0, 'In Stock'),
('Tangerine', 'Venice', 0, 0, 'In Production'),
('Tangerine', 'Venice', 0, 0, 'Produced'),
('Tangerine', 'Venice', 0, 0, 'In Stock'),
('Tangerine', 'Washington', 0, 0, 'In Production'),
('Tangerine', 'Washington', 0, 0, 'Produced'),
('Tangerine', 'Washington', 0, 0, 'In Stock'),
('Tangerine', 'Inner Planter', 0, 0, 'In Production'),
('Tangerine', 'Inner Planter', 0, 0, 'Produced'),
('Tangerine', 'Inner Planter', 0, 0, 'In Stock'),
('Tangerine', 'Outer Planter', 0, 0, 'In Production'),
('Tangerine', 'Outer Planter', 0, 0, 'Produced'),
('Tangerine', 'Outer Planter', 0, 0, 'In Stock'),
('Terracotta', 'Atlanta', 0, 0, 'In Production'),
('Terracotta', 'Atlanta', 0, 0, 'Produced'),
('Terracotta', 'Atlanta', 0, 0, 'In Stock'),
('Terracotta', 'Boston', 0, 0, 'In Production'),
('Terracotta', 'Boston', 0, 0, 'Produced'),
('Terracotta', 'Boston', 0, 0, 'In Stock'),
('Terracotta', 'Carmel', 0, 0, 'In Production'),
('Terracotta', 'Carmel', 0, 0, 'Produced'),
('Terracotta', 'Carmel', 0, 0, 'In Stock'),
('Terracotta', 'Charleston', 0, 0, 'In Production'),
('Terracotta', 'Charleston', 0, 0, 'Produced'),
('Terracotta', 'Charleston', 0, 0, 'In Stock'),
('Terracotta', 'Chicago', 0, 0, 'In Production'),
('Terracotta', 'Chicago', 0, 0, 'Produced'),
('Terracotta', 'Chicago', 0, 0, 'In Stock'),
('Terracotta', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Terracotta', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Terracotta', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Terracotta', 'Denver', 0, 0, 'In Production'),
('Terracotta', 'Denver', 0, 0, 'Produced'),
('Terracotta', 'Denver', 0, 0, 'In Stock'),
('Terracotta', 'HD Round', 0, 0, 'In Production'),
('Terracotta', 'HD Round', 0, 0, 'Produced'),
('Terracotta', 'HD Round', 0, 0, 'In Stock'),
('Terracotta', 'Houston', 0, 0, 'In Production'),
('Terracotta', 'Houston', 0, 0, 'Produced'),
('Terracotta', 'Houston', 0, 0, 'In Stock'),
('Terracotta', 'Manhattan', 0, 0, 'In Production'),
('Terracotta', 'Manhattan', 0, 0, 'Produced'),
('Terracotta', 'Manhattan', 0, 0, 'In Stock'),
('Terracotta', 'Mini Manhattan', 0, 0, 'In Production'),
('Terracotta', 'Mini Manhattan', 0, 0, 'Produced'),
('Terracotta', 'Mini Manhattan', 0, 0, 'In Stock'),
('Terracotta', 'Miami', 0, 0, 'In Production'),
('Terracotta', 'Miami', 0, 0, 'Produced'),
('Terracotta', 'Miami', 0, 0, 'In Stock'),
('Terracotta', 'Mini Miami', 0, 0, 'In Production'),
('Terracotta', 'Mini Miami', 0, 0, 'Produced'),
('Terracotta', 'Mini Miami', 0, 0, 'In Stock'),
('Terracotta', 'Michu', 0, 0, 'In Production'),
('Terracotta', 'Michu', 0, 0, 'Produced'),
('Terracotta', 'Michu', 0, 0, 'In Stock'),
('Terracotta', 'Michu Planter', 0, 0, 'In Production'),
('Terracotta', 'Michu Planter', 0, 0, 'Produced'),
('Terracotta', 'Michu Planter', 0, 0, 'In Stock'),
('Terracotta', 'Minima', 0, 0, 'In Production'),
('Terracotta', 'Minima', 0, 0, 'Produced'),
('Terracotta', 'Minima', 0, 0, 'In Stock'),
('Terracotta', 'New York', 0, 0, 'In Production'),
('Terracotta', 'New York', 0, 0, 'Produced'),
('Terracotta', 'New York', 0, 0, 'In Stock'),
('Terracotta', 'New York 100', 0, 0, 'In Production'),
('Terracotta', 'New York 100', 0, 0, 'Produced'),
('Terracotta', 'New York 100', 0, 0, 'In Stock'),
('Terracotta', 'Orlando', 0, 0, 'In Production'),
('Terracotta', 'Orlando', 0, 0, 'Produced'),
('Terracotta', 'Orlando', 0, 0, 'In Stock'),
('Terracotta', 'Portland', 0, 0, 'In Production'),
('Terracotta', 'Portland', 0, 0, 'Produced'),
('Terracotta', 'Portland', 0, 0, 'In Stock'),
('Terracotta', 'Phoenix', 0, 0, 'In Production'),
('Terracotta', 'Phoenix', 0, 0, 'Produced'),
('Terracotta', 'Phoenix', 0, 0, 'In Stock'),
('Terracotta', 'Reno', 0, 0, 'In Production'),
('Terracotta', 'Reno', 0, 0, 'Produced'), 
('Terracotta', 'Reno', 0, 0, 'In Stock'),
('Terracotta', 'San Francisco New Mold', 0, 0, 'In Production'),
('Terracotta', 'San Francisco New Mold', 0, 0, 'Produced'),
('Terracotta', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Terracotta', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Terracotta', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Terracotta', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Terracotta', 'San Francisco ADA', 0, 0, 'In Production'),
('Terracotta', 'San Francisco ADA', 0, 0, 'Produced'),
('Terracotta', 'San Francisco ADA', 0, 0, 'In Stock'),
('Terracotta', 'Mini San Francisco', 0, 0, 'In Production'),
('Terracotta', 'Mini San Francisco', 0, 0, 'Produced'),
('Terracotta', 'Mini San Francisco', 0, 0, 'In Stock'),
('Terracotta', 'Seattle', 0, 0, 'In Production'),
('Terracotta', 'Seattle', 0, 0, 'Produced'),
('Terracotta', 'Seattle', 0, 0, 'In Stock'),
('Terracotta', 'Texas', 0, 0, 'In Production'),
('Terracotta', 'Texas', 0, 0, 'Produced'),
('Terracotta', 'Texas', 0, 0, 'In Stock'),
('Terracotta', 'Vegas 80', 0, 0, 'In Production'),
('Terracotta', 'Vegas 80', 0, 0, 'Produced'),
('Terracotta', 'Vegas 80', 0, 0, 'In Stock'),
('Terracotta', 'Vegas 60', 0, 0, 'In Production'),
('Terracotta', 'Vegas 60', 0, 0, 'Produced'),
('Terracotta', 'Vegas 60', 0, 0, 'In Stock'),
('Terracotta', 'Venice', 0, 0, 'In Production'),
('Terracotta', 'Venice', 0, 0, 'Produced'),
('Terracotta', 'Venice', 0, 0, 'In Stock'),
('Terracotta', 'Washington', 0, 0, 'In Production'),
('Terracotta', 'Washington', 0, 0, 'Produced'),
('Terracotta', 'Washington', 0, 0, 'In Stock'),
('Terracotta', 'Inner Planter', 0, 0, 'In Production'),
('Terracotta', 'Inner Planter', 0, 0, 'Produced'),
('Terracotta', 'Inner Planter', 0, 0, 'In Stock'),
('Terracotta', 'Outer Planter', 0, 0, 'In Production'),
('Terracotta', 'Outer Planter', 0, 0, 'Produced'),
('Terracotta', 'Outer Planter', 0, 0, 'In Stock'),
('Turquoise', 'Atlanta', 0, 0, 'In Production'),
('Turquoise', 'Atlanta', 0, 0, 'Produced'),
('Turquoise', 'Atlanta', 0, 0, 'In Stock'),
('Turquoise', 'Boston', 0, 0, 'In Production'),
('Turquoise', 'Boston', 0, 0, 'Produced'),
('Turquoise', 'Boston', 0, 0, 'In Stock'),
('Turquoise', 'Carmel', 0, 0, 'In Production'),
('Turquoise', 'Carmel', 0, 0, 'Produced'),
('Turquoise', 'Carmel', 0, 0, 'In Stock'),
('Turquoise', 'Charleston', 0, 0, 'In Production'),
('Turquoise', 'Charleston', 0, 0, 'Produced'),
('Turquoise', 'Charleston', 0, 0, 'In Stock'),
('Turquoise', 'Chicago', 0, 0, 'In Production'),
('Turquoise', 'Chicago', 0, 0, 'Produced'),
('Turquoise', 'Chicago', 0, 0, 'In Stock'),
('Turquoise', 'Concrete Drain Covers', 0, 0, 'In Production'),
('Turquoise', 'Concrete Drain Covers', 0, 0, 'Produced'),
('Turquoise', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('Turquoise', 'Denver', 0, 0, 'In Production'),
('Turquoise', 'Denver', 0, 0, 'Produced'),
('Turquoise', 'Denver', 0, 0, 'In Stock'),
('Turquoise', 'HD Round', 0, 0, 'In Production'),
('Turquoise', 'HD Round', 0, 0, 'Produced'),
('Turquoise', 'HD Round', 0, 0, 'In Stock'),
('Turquoise', 'Houston', 0, 0, 'In Production'),
('Turquoise', 'Houston', 0, 0, 'Produced'),
('Turquoise', 'Houston', 0, 0, 'In Stock'),
('Turquoise', 'Manhattan', 0, 0, 'In Production'),
('Turquoise', 'Manhattan', 0, 0, 'Produced'),
('Turquoise', 'Manhattan', 0, 0, 'In Stock'),
('Turquoise', 'Mini Manhattan', 0, 0, 'In Production'),
('Turquoise', 'Mini Manhattan', 0, 0, 'Produced'),
('Turquoise', 'Mini Manhattan', 0, 0, 'In Stock'),
('Turquoise', 'Miami', 0, 0, 'In Production'),
('Turquoise', 'Miami', 0, 0, 'Produced'),
('Turquoise', 'Miami', 0, 0, 'In Stock'),
('Turquoise', 'Mini Miami', 0, 0, 'In Production'),
('Turquoise', 'Mini Miami', 0, 0, 'Produced'),
('Turquoise', 'Mini Miami', 0, 0, 'In Stock'),
('Turquoise', 'Michu', 0, 0, 'In Production'),
('Turquoise', 'Michu', 0, 0, 'Produced'),
('Turquoise', 'Michu', 0, 0, 'In Stock'),
('Turquoise', 'Michu Planter', 0, 0, 'In Production'),
('Turquoise', 'Michu Planter', 0, 0, 'Produced'),
('Turquoise', 'Michu Planter', 0, 0, 'In Stock'),
('Turquoise', 'Minima', 0, 0, 'In Production'),
('Turquoise', 'Minima', 0, 0, 'Produced'),
('Turquoise', 'Minima', 0, 0, 'In Stock'),
('Turquoise', 'New York', 0, 0, 'In Production'),
('Turquoise', 'New York', 0, 0, 'Produced'),
('Turquoise', 'New York', 0, 0, 'In Stock'),
('Turquoise', 'New York 100', 0, 0, 'In Production'),
('Turquoise', 'New York 100', 0, 0, 'Produced'),
('Turquoise', 'New York 100', 0, 0, 'In Stock'),
('Turquoise', 'Orlando', 0, 0, 'In Production'),
('Turquoise', 'Orlando', 0, 0, 'Produced'),
('Turquoise', 'Orlando', 0, 0, 'In Stock'),
('Turquoise', 'Portland', 0, 0, 'In Production'),
('Turquoise', 'Portland', 0, 0, 'Produced'),
('Turquoise', 'Portland', 0, 0, 'In Stock'),
('Turquoise', 'Phoenix', 0, 0, 'In Production'),
('Turquoise', 'Phoenix', 0, 0, 'Produced'),
('Turquoise', 'Phoenix', 0, 0, 'In Stock'),
('Turquoise', 'Reno', 0, 0, 'In Production'),
('Turquoise', 'Reno', 0, 0, 'Produced'),
('Turquoise', 'Reno', 0, 0, 'In Stock'),
('Turquoise', 'San Francisco New Mold', 0, 0, 'In Production'),
('Turquoise', 'San Francisco New Mold', 0, 0, 'Produced'),
('Turquoise', 'San Francisco New Mold', 0, 0, 'In Stock'),
('Turquoise', 'San Francisco Old Mold', 0, 0, 'In Production'),
('Turquoise', 'San Francisco Old Mold', 0, 0, 'Produced'),
('Turquoise', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('Turquoise', 'San Francisco ADA', 0, 0, 'In Production'),
('Turquoise', 'San Francisco ADA', 0, 0, 'Produced'),
('Turquoise', 'San Francisco ADA', 0, 0, 'In Stock'),
('Turquoise', 'Mini San Francisco', 0, 0, 'In Production'),
('Turquoise', 'Mini San Francisco', 0, 0, 'Produced'),
('Turquoise', 'Mini San Francisco', 0, 0, 'In Stock'),
('Turquoise', 'Seattle', 0, 0, 'In Production'),
('Turquoise', 'Seattle', 0, 0, 'Produced'),
('Turquoise', 'Seattle', 0, 0, 'In Stock'),
('Turquoise', 'Texas', 0, 0, 'In Production'),
('Turquoise', 'Texas', 0, 0, 'Produced'),
('Turquoise', 'Texas', 0, 0, 'In Stock'),
('Turquoise', 'Vegas 80', 0, 0, 'In Production'),
('Turquoise', 'Vegas 80', 0, 0, 'Produced'),
('Turquoise', 'Vegas 80', 0, 0, 'In Stock'),
('Turquoise', 'Vegas 60', 0, 0, 'In Production'),
('Turquoise', 'Vegas 60', 0, 0, 'Produced'),
('Turquoise', 'Vegas 60', 0, 0, 'In Stock'),
('Turquoise', 'Venice', 0, 0, 'In Production'),
('Turquoise', 'Venice', 0, 0, 'Produced'),
('Turquoise', 'Venice', 0, 0, 'In Stock'),
('Turquoise', 'Washington', 0, 0, 'In Production'),
('Turquoise', 'Washington', 0, 0, 'Produced'),
('Turquoise', 'Washington', 0, 0, 'In Stock'),
('Turquoise', 'Inner Planter', 0, 0, 'In Production'),
('Turquoise', 'Inner Planter', 0, 0, 'Produced'),
('Turquoise', 'Inner Planter', 0, 0, 'In Stock'),
('Turquoise', 'Outer Planter', 0, 0, 'In Production'),
('Turquoise', 'Outer Planter', 0, 0, 'Produced'),
('Turquoise', 'Outer Planter', 0, 0, 'In Stock'),
('White', 'Atlanta', 0, 0, 'In Production'),
('White', 'Atlanta', 0, 0, 'Produced'),
('White', 'Atlanta', 0, 0, 'In Stock'),
('White', 'Boston', 0, 0, 'In Production'),
('White', 'Boston', 0, 0, 'Produced'),
('White', 'Boston', 0, 0, 'In Stock'),
('White', 'Carmel', 0, 0, 'In Production'),
('White', 'Carmel', 0, 0, 'Produced'),
('White', 'Carmel', 0, 0, 'In Stock'),
('White', 'Charleston', 0, 0, 'In Production'),
('White', 'Charleston', 0, 0, 'Produced'),
('White', 'Charleston', 0, 0, 'In Stock'),
('White', 'Chicago', 0, 0, 'In Production'),
('White', 'Chicago', 0, 0, 'Produced'),
('White', 'Chicago', 0, 0, 'In Stock'),
('White', 'Concrete Drain Covers', 0, 0, 'In Production'),
('White', 'Concrete Drain Covers', 0, 0, 'Produced'),
('White', 'Concrete Drain Covers', 0, 0, 'In Stock'),
('White', 'Denver', 0, 0, 'In Production'),
('White', 'Denver', 0, 0, 'Produced'),
('White', 'Denver', 0, 0, 'In Stock'),
('White', 'HD Round', 0, 0, 'In Production'),
('White', 'HD Round', 0, 0, 'Produced'), 
('White', 'HD Round', 0, 0, 'In Stock'),
('White', 'Houston', 0, 0, 'In Production'),
('White', 'Houston', 0, 0, 'Produced'),
('White', 'Houston', 0, 0, 'In Stock'),
('White', 'Manhattan', 0, 0, 'In Production'),
('White', 'Manhattan', 0, 0, 'Produced'),
('White', 'Manhattan', 0, 0, 'In Stock'),
('White', 'Mini Manhattan', 0, 0, 'In Production'),
('White', 'Mini Manhattan', 0, 0, 'Produced'),
('White', 'Mini Manhattan', 0, 0, 'In Stock'),
('White', 'Miami', 0, 0, 'In Production'),
('White', 'Miami', 0, 0, 'Produced'),
('White', 'Miami', 0, 0, 'In Stock'),
('White', 'Mini Miami', 0, 0, 'In Production'),
('White', 'Mini Miami', 0, 0, 'Produced'),
('White', 'Mini Miami', 0, 0, 'In Stock'),
('White', 'Michu', 0, 0, 'In Production'),
('White', 'Michu', 0, 0, 'Produced'),
('White', 'Michu', 0, 0, 'In Stock'),
('White', 'Michu Planter', 0, 0, 'In Production'),
('White', 'Michu Planter', 0, 0, 'Produced'),
('White', 'Michu Planter', 0, 0, 'In Stock'),
('White', 'Minima', 0, 0, 'In Production'),
('White', 'Minima', 0, 0, 'Produced'),
('White', 'Minima', 0, 0, 'In Stock'),
('White', 'New York', 0, 0, 'In Production'),
('White', 'New York', 0, 0, 'Produced'),
('White', 'New York', 0, 0, 'In Stock'),
('White', 'New York 100', 0, 0, 'In Production'),
('White', 'New York 100', 0, 0, 'Produced'),
('White', 'New York 100', 0, 0, 'In Stock'),
('White', 'Orlando', 0, 0, 'In Production'),
('White', 'Orlando', 0, 0, 'Produced'),
('White', 'Orlando', 0, 0, 'In Stock'),
('White', 'Portland', 0, 0, 'In Production'),
('White', 'Portland', 0, 0, 'Produced'),
('White', 'Portland', 0, 0, 'In Stock'),
('White', 'Phoenix', 0, 0, 'In Production'),
('White', 'Phoenix', 0, 0, 'Produced'),
('White', 'Phoenix', 0, 0, 'In Stock'),
('White', 'Reno', 0, 0, 'In Production'),
('White', 'Reno', 0, 0, 'Produced'),
('White', 'Reno', 0, 0, 'In Stock'),
('White', 'San Francisco New Mold', 0, 0, 'In Production'),
('White', 'San Francisco New Mold', 0, 0, 'Produced'),
('White', 'San Francisco New Mold', 0, 0, 'In Stock'),
('White', 'San Francisco Old Mold', 0, 0, 'In Production'),
('White', 'San Francisco Old Mold', 0, 0, 'Produced'),
('White', 'San Francisco Old Mold', 0, 0, 'In Stock'),
('White', 'San Francisco ADA', 0, 0, 'In Production'),
('White', 'San Francisco ADA', 0, 0, 'Produced'),
('White', 'San Francisco ADA', 0, 0, 'In Stock'),
('White', 'Mini San Francisco', 0, 0, 'In Production'),
('White', 'Mini San Francisco', 0, 0, 'Produced'),
('White', 'Mini San Francisco', 0, 0, 'In Stock'),
('White', 'Seattle', 0, 0, 'In Production'),
('White', 'Seattle', 0, 0, 'Produced'),
('White', 'Seattle', 0, 0, 'In Stock'),
('White', 'Texas', 0, 0, 'In Production'),
('White', 'Texas', 0, 0, 'Produced'),
('White', 'Texas', 0, 0, 'In Stock'),
('White', 'Vegas 80', 0, 0, 'In Production'),
('White', 'Vegas 80', 0, 0, 'Produced'),
('White', 'Vegas 80', 0, 0, 'In Stock'),
('White', 'Vegas 60', 0, 0, 'In Production'),
('White', 'Vegas 60', 0, 0, 'Produced'),
('White', 'Vegas 60', 0, 0, 'In Stock'),
('White', 'Venice', 0, 0, 'In Production'),
('White', 'Venice', 0, 0, 'Produced'),
('White', 'Venice', 0, 0, 'In Stock'),
('White', 'Washington', 0, 0, 'In Production'),
('White', 'Washington', 0, 0, 'Produced'),
('White', 'Washington', 0, 0, 'In Stock'),
('White', 'Inner Planter', 0, 0, 'In Production'),
('White', 'Inner Planter', 0, 0, 'Produced'),
('White', 'Inner Planter', 0, 0, 'In Stock'),
('White', 'Outer Planter', 0, 0, 'In Production'),
('White', 'Outer Planter', 0, 0, 'Produced'),
('White', 'Outer Planter', 0, 0, 'In Stock');

COMMIT;